/* Reviewed Swedish teaching content. Stable IDs are independent of titles. No private data. */
(function(root){
  'use strict';
  const categories=[['start','Kom igång'],['saving','Sparande & kostnader'],['statements','Förstå bolaget'],['valuation','Värdering'],['macro','Makro'],['research','Din egen analys']].map(([id,title])=>({id,title}));
  const sources={
    stocks:['Investor.gov: aktier','https://www.investor.gov/introduction-investing/investing-basics/investment-products/stocks'],
    funds:['Investor.gov: ETF och fondstruktur','https://www.investor.gov/introduction-investing/investing-basics/investment-products/mutual-funds-and-exchange-traded-2'],
    risk:['Investor.gov: riskspridning','https://www.investor.gov/introduction-investing/getting-started/asset-allocation'],
    fees:['Investor.gov: avgifter','https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/updated'],
    reports:['SEC: finansiella rapporters struktur','https://www.sec.gov/about/reports-publications/investorpubsbegfinstmtguide'],
    tax:['Skatteverket: investeringssparkonto','https://www.skatteverket.se/privat/skatter/vardepapper/investeringssparkontoisk.4.5fc8c94513259a4ba1d800037851.html'],
    inflation:['Riksbanken: inflationsmått','https://www.riksbank.se/sv/penningpolitik/inflationsmalet/hur-mats-inflation/'],
    rates:['Riksbanken: penningpolitik','https://www.riksbank.se/sv/penningpolitik/vad-ar-penningpolitik/']
  };
  // Definition, practical relevance, original worked example, depth, misconception,
  // exercise, related concepts, connected destination, reference (if applicable).
  const rows=[
    ['aktier','Vad är en aktie?','start','ägande börsvärde market cap utdelning',
      'En aktie är en ägarandel i ett bolag. Värdet kan förändras och bolaget kan dela ut pengar, men varken kursuppgång eller utdelning är garanterad.',
      'Börja med verksamheten: vem betalar bolaget, för vad och varför? En låg kurs i kronor säger inget om hur billigt hela bolaget är. Antalet aktier måste också vara känt.',
      'Ett fiktivt bolag har en miljon aktier och kursen 50 kr. Börsvärdet är 50 miljoner kr. Köper du 100 aktier äger du 0,01 procent, inte 100 kronor av bolagets vinst. Din kostnad är 5 000 kr före courtage.',
      'Olika aktieslag kan ge olika rösträtt. Börsvärde beskriver ägarnas marknadsvärde och skiljer sig från företagsvärde, som även tar hänsyn till finansiering. Vid konkurs står aktieägare normalt efter långivare. Det kan innebära att hela insatsen förloras.',
      'Blanda inte ihop en bra produkt med ett attraktivt pris på aktien. Dela inte bolagets vinst med ditt eget antal aktier.',
      'Öppna Research och beskriv med en mening hur ett bolag tjänar pengar. Kontrollera därefter vilket aktieslag och vilken valuta du tittar på.', ['revenue','risk'],'workflow-manual-thesis','stocks'],
    ['fonder','Vad är en fond?','start','fondandel indexfond aktiv förvaltning',
      'En fond samlar många sparares pengar och placerar dem enligt en bestämd inriktning. Du äger fondandelar och får därigenom en andel av fondens tillgångar.',
      'En fond kan göra det lättare att sprida ett mindre sparande. Läs ändå vad den faktiskt äger: en smal branschfond kan vara mer koncentrerad än namnet antyder.',
      'Du köper andelar för 2 000 kr till andelsvärdet 200 kr och får tio andelar. Om värdet senare är 220 kr är innehavet värt 2 200 kr före eventuell skatt. En insättning är inte i sig avkastning.',
      'En indexfond följer ett valt index; en aktiv fond gör egna urval. Index skiljer sig i länder, bolagsstorlek och viktning. Jämför därför fonder med liknande innehåll och risk, inte bara senaste årets avkastning. Läs faktabladets kostnader, riskindikator och rekommenderade innehavstid.',
      'Fem fonder kan äga samma stora bolag. Fler fondnamn betyder inte automatiskt bättre riskspridning.',
      'Jämför två hypotetiska fondavgifter i avgiftsverktyget. Håll avkastning och sparande lika så att du ser just avgiftens effekt.', ['fees','diversifiering'],'tool-fees','funds'],
    ['etf','ETF: en fond som handlas på börsen','start','börshandlad fond exchange traded fund',
      'ETF betyder börshandlad fond. Du köper och säljer andelar på börsen, ungefär som aktier, medan innehållet följer fondens mandat.',
      'Utöver fondavgiften behöver du förstå courtage, köp- och säljkurs samt eventuell valutaväxling. Små och täta affärer kan bli dyra även när den årliga fondavgiften är låg.',
      'En ETF har köpkurs 100,20 kr och säljkurs 100 kr. Köper du tio andelar och säljer direkt utan marknadsrörelse förlorar du 2 kr på skillnaden, plus eventuellt courtage. Denna spread är en handelskostnad.',
      'Marknadspriset kan avvika från värdet på fondens underliggande tillgångar. Likviditet, öppettider och fondens struktur spelar roll. En ETF kan vara bred, smal, utdelande eller återinvesterande. Hävstångsprodukter har annan risk och ingår inte i denna nybörjarövning.',
      'ETF betyder varken automatiskt indexfond, låg risk eller ingen valutarisk. Handel i SEK säger inte vilken valuta tillgångarna är exponerade mot.',
      'Räkna på en liten respektive stor order med samma courtage. Skriv sedan upp vilka kostnader som saknas i jämförelsen.', ['fees','currency'],'tool-purchase','funds'],
    ['avkastning','Avkastning: vad har pengarna gett?','start','totalavkastning kursvinst utdelning',
      'Avkastning är värdeförändringen på en investering, inklusive relevanta utdelningar, i förhållande till det investerade beloppet. Ange alltid period och valuta.',
      'Kontots saldo kan öka för att du sätter in pengar. Det betyder inte att investeringarna har gått upp. Skilj dina insättningar från investeringens resultat när du följer upp.',
      'En aktie köps för 100 kr, säljs för 108 kr och ger 2 kr i utdelning under tiden. Utan avgifter och skatt blir avkastningen (108 + 2 − 100) / 100 = 10 procent. Kursuppgången ensam är 8 procent.',
      'Exemplet gäller ett köp utan nya insättningar. Vid löpande kassaflöden behövs en metod som tar hänsyn till deras tidpunkter, exempelvis pengaviktad avkastning. Återinvesterade utdelningar påverkar också senare värde. Jämför inte ett prisindex med en portfölj inklusive utdelningar utan att ange skillnaden.',
      'En utdelning är inte gratis extravärde oberoende av aktiekursen. Dra inte slutsatser om årsavkastning från en enskild månad.',
      'Ange startvärde, slutvärde och period i avkastningsverktyget. Kontrollera att exemplet inte innehåller insättningar eller utdelningar som du glömt.', ['cagr','currency'],'tool-return',null],
    ['risk','Risk är mer än svängande kurser','start','volatilitet förlust återhämtning',
      'Risk är osäkerheten kring utfallet och möjligheten att förlora pengar. Kurssvängningar är en del av risken, men även tidshorisont, belåning och bolagets överlevnad spelar roll.',
      'Pengar du behöver snart kan tvinga fram en försäljning i ett dåligt läge. Fråga både hur mycket värdet kan falla och vad ett sådant fall skulle innebära för din ekonomi.',
      '100 kr faller med 10 procent till 90 kr. En uppgång med 10 procent ger sedan 99 kr. För att komma tillbaka till 100 krävs 100 / 90 − 1, ungefär 11,1 procent.',
      'Volatilitet beskriver variation, inte hela sannolikheten för permanent förlust. Likviditetsrisk betyder att en tillgång kan vara svår att sälja till rimligt pris. Belåning kan skapa tvångsförsäljningar. Historiska fall är användbara stresstest men sätter ingen övre gräns för framtida förluster.',
      'Låg historisk volatilitet är ingen garanti. Förväxla inte din vilja att ta risk med din ekonomiska förmåga att bära en förlust.',
      'Gör ett lägre scenario i värderingsverktyget. Skriv vilken konsekvens ett halverat värde skulle få, utan att ändra prognosen för att den känns obekväm.', ['diversifiering','scenarios'],'tool-scenarios','risk'],
    ['diversifiering','Diversifiering: sprid det som kan gå fel','start','riskspridning portfölj korrelation',
      'Diversifiering betyder att sprida investeringarna så att utfallet inte beror på en enda sak. Det kan minska koncentrationsrisk men tar inte bort all marknadsrisk.',
      'Räkna inte bara innehav. Titta på gemensamma kunder, räntor, råvaror, länder och valutor. Flera bolag kan påverkas av samma händelse samtidigt.',
      'En portfölj med fem lika stora bolag förlorar 10 procent om ett av bolagen halveras och de andra står stilla. Om alla fem halveras förlorar portföljen 50 procent. Antalet innehav skyddar inte mot en gemensam chock.',
      'Korrelation beskriver hur värden rör sig tillsammans under en viss period och kan ändras. Portföljvikter förändras när kurserna rör sig. Ombalansering återställer en vald fördelning men kan medföra avgifter och skatt. En lämplig fördelning beror på mål och tid, inte på ett universellt antal aktier.',
      'Två olika fondnamn kan dölja nästan samma innehåll. Ett gemensamt tekniktema blir inte oberoende risk bara för att bolagen har olika produkter.',
      'Skriv två risker som flera av dina tänkta innehav delar. Lägg dem som tydliga antaganden i en manuell tes.', ['risk','thesis'],'workflow-manual-thesis','risk'],
    ['compounding','Ränta på ränta','saving','sammansatt avkastning återinvestering',
      'Ränta på ränta innebär att tidigare avkastning också kan ge avkastning. För investeringar är framtida avkastning osäker; en jämn räntesats är ett räkneantagande.',
      'Tid, avgifter och återinvestering påverkar hur mycket kapitalet kan växa. Regelbundet sparande ökar kapitalet, men är en egen insats och ska inte räknas som intjänad avkastning.',
      '1 000 kr växer med antagna 5 procent till 1 050 kr första året. Andra årets 5 procent är 52,50 kr, så summan blir 1 102,50 kr. Skillnaden beror på att även första årets 50 kr får växa.',
      'Utan insättningar är slutvärdet startvärde × (1 + r)^n. Med insättningar spelar deras tidpunkt roll. NTM:s kalkyl visar sin modell för sparande, avgift och inflation; verkliga marknadsrörelser sker inte jämnt. En negativ period påverkar kapitalet som kommande procentförändringar räknas på.',
      'Fem procents antagen avkastning är inte ett löfte. Jämför inte nominella framtida kronor direkt med dagens köpkraft.',
      'Pröva tio och tjugo år i sparverktyget med samma startkapital. Ändra sedan bara avgiften och jämför skillnaden.', ['fees','inflation'],'tool-compound',null],
    ['fees','Avgifter och courtage','saving','fondavgift handelsavgift spread kostnader',
      'Avgifter minskar det kapital som kan arbeta vidare. Courtage är en avgift för en affär; en fondavgift tas löpande och har därför en annan effekt.',
      'Jämför kostnader för samma investeringstid och samma belopp. En minimiavgift kan dominera små köp, medan en årlig procentsats får stor betydelse för ett långvarigt sparande.',
      'Ett courtage på 19 kr är 1,9 procent av ett köp på 1 000 kr men 0,19 procent av ett köp på 10 000 kr. En försäljning kan medföra ytterligare courtage. Exemplet antar en fast avgift per affär.',
      'I en förenklad årsmodell lämnar 7 procents bruttoavkastning och 1 procents avgift cirka 6 procent före skatt och inflation. Verklig avgiftsdebitering kan ske löpande. Spread, valutapåslag och transaktionskostnader kan tillkomma utöver den annonserade fondavgiften. Håll därför metod och omfattning lika.',
      'Lägst avgift betyder inte att två produkter ger samma exponering. Dra inte av en fondavgift en gång till från en avkastning som redan redovisas efter avgifter.',
      'Jämför 0,2 och 1 procent i avgiftsverktyget med samma egna avkastningsantagande. Resultatet isolerar kostnaden, inte vilken fond som är bäst.', ['compounding','gav'],'tool-fees','fees'],
    ['gav','GAV: genomsnittligt anskaffningsvärde','saving','snittpris inköpspris anskaffningsvärde',
      'GAV beskriver ditt genomsnittliga inköpspris per aktie. Det hjälper dig att förstå kostnaden för innehavet men säger inget om bolagets framtida värde.',
      'Ett tilläggsköp ändrar både kostnad och exponering. Ett lägre GAV är inte i sig ett bättre investeringsbeslut om bolagets utsikter har försämrats.',
      'Du köper tio aktier för 100 kr styck och tio för 80 kr styck. Kostnaden är 1 800 kr för tjugo aktier, vilket ger GAV 90 kr utan avgifter. Med 20 kr courtage på varje köp blir kostnadsbasen i denna övning 1 840 kr, alltså 92 kr per aktie.',
      'Räkna viktat efter antal aktier, inte som ett enkelt medel av alla orderkurser. En split ändrar pris och antal utan att skapa värde. Skattemässigt omkostnadsbelopp och kontots visade GAV kan behandla händelser olika; köpverktyget ersätter inte en deklarationsberäkning.',
      'Att köpa mer enbart för att sänka snittpriset kan öka en risk du inte längre vill ha. Det gamla inköpspriset bestämmer inte framtida avkastning.',
      'Pröva samma tilläggsköp med två olika orderstorlekar. Öppna sedan tesen och skriv varför du skulle vilja öka innehavet i dag.', ['fees','thesis'],'tool-purchase',null],
    ['isk','ISK: konto och beskattningsmodell','saving','investeringssparkonto schablonskatt kapitalunderlag',
      'ISK är en kontoform, inte en investering. Beskattningen bygger på ett schablonunderlag enligt reglerna för inkomståret, i stället för skatt på varje enskild realiserad vinst.',
      'Kontoval och placeringsval är skilda frågor. En förlust gör inte automatiskt schablonskatten noll. Kontrollera vilket inkomstår och vilka sparformer en skattefri grundnivå omfattar.',
      'Som principövning: ett underlag på 100 000 kr och en helt hypotetisk effektiv skattesats på 1 procent ger 1 000 kr. Detta är inte årets skattesats och bortser från grundnivåer. Använd det årsvalda verktyget för aktuella regler.',
      'Kapitalunderlaget är inte bara dagens saldo; tidpunkter och insättningar spelar roll. Den skattefria grundnivån gäller enligt reglerna för det sammanlagda berörda sparandet, inte ett nytt fullt avdrag per konto. NTM hämtar regelinformationen från sin daterade regelregistrering och visar begränsningarna i skattekalkylen.',
      'Använd inte en gammal procentsats som om den gällde varje år. ISK gör inte en riskfylld tillgång säker och är inte samma sak som insättningsgaranti.',
      'Öppna ISK-kalkylen, välj inkomstår och läs regelkortet innan du anger ditt eget underlag. Kontrollera sedan källan hos Skatteverket.', ['fees','risk'],'tool-tax','tax'],
    ['currency','Valutarisk och avkastning i SEK','saving','FX valutajusterad avkastning dollar usd sek',
      'Avkastning i en utländsk valuta är inte samma sak som avkastning i kronor. Både investeringens pris och valutakursen påverkar vad du får i SEK.',
      'Ange tydligt hur valutakursen mäts. Fler SEK per USD betyder att dollarn har stärkts mot kronan, vilket höjer SEK-värdet på ett oförändrat dollarbelopp.',
      'En investering stiger 10 procent i USD samtidigt som USD blir 5 procent billigare i SEK. Utfallet blir 1,10 × 0,95 − 1 = 4,5 procent i SEK, inte 5 procent. Exemplet bortser från avgifter, skatt och kassaflöden.',
      'Procentförändringarna multipliceras eftersom valutaförändringen gäller hela det nya dollarvärdet. Valutasäkrade produkter har egna kostnader och villkor. Ett bolag kan dessutom ha intäkter och kostnader i flera valutor, så noteringsvalutan beskriver inte hela verksamhetens exponering.',
      'Att addera aktie- och valutaprocent ger bara en approximation. Kontrollera att du inte har vänt valutaparet när du räknar.',
      'Använd FX-verktyget med +10 procent för aktien och −5 procent för valutan. Vänd sedan tecknet på valutan och jämför.', ['avkastning','risk'],'tool-fx',null],
    ['revenue','Omsättning: försäljning före resultat','statements','revenue intäkter försäljning',
      'Omsättning beskriver intäkter under en period. Den är inte samma sak som vinst och behöver inte betyda att kunden redan har betalat kontant.',
      'Tillväxt är lättare att förstå när du vet om den kommer från fler kunder, högre priser, förvärv eller valuta. Samma procenttal kan dölja helt olika affärsutveckling.',
      'Ett fiktivt bolag säljer 1 000 abonnemang för 100 kr vardera under månaden. Intäkten i den förenklade övningen är 100 000 kr. Med 90 000 kr i kostnader återstår 10 000 kr före de poster som exemplet inte tar med.',
      'Läs redovisningsprincipen och periodens längd. En kvartalssiffra ska inte jämföras direkt med ett halvårsbelopp. Bruttohandel kan redovisas med stora motsvarande kostnader, medan en förmedlare kan redovisa sin ersättning netto. Banker och andra specialprofiler kräver därför egna intäktsdefinitioner.',
      'Snabbare omsättningstillväxt innebär inte automatiskt högre värde per aktie. Jämför inte olika intäktsdefinitioner som om de vore identiska.',
      'Öppna källinformationen för intäkter i Research. Notera perioden, definitionen och om beloppet är rapporterat eller beräknat.', ['marginal','eps'],'research-nvda',null],
    ['eps','EPS: vinst per aktie','statements','vinst per aktie earnings per share diluted',
      'EPS visar resultat per aktie för en angiven period. Utspädd EPS tar även hänsyn till vissa potentiella aktier enligt redovisningsreglerna.',
      'Din andel av vinsten kan utvecklas annorlunda än hela bolagets vinst. Kontrollera därför både resultatet, antalet aktier och vilken period EPS avser.',
      'I ett förenklat bolag är resultatet till stamaktier 10 miljoner kr och det genomsnittliga antalet aktier två miljoner. EPS är 5 kr. Om vinsten är oförändrad men antalet aktier ökar till 2,5 miljoner blir EPS 4 kr.',
      'Det relevanta antalet är normalt ett vägt genomsnitt under perioden, inte dagens antal. Preferensvillkor, förluster, optioner och splitjusteringar kan göra utspädd EPS mer komplex. Justerad EPS kan exkludera kostnader; jämför då avstämningen med redovisad EPS. Saknad jämförbar aktiebas ska inte ersättas med en gissning.',
      'Dela inte historisk vinst med dagens aktier utan att kontrollera grunden. Års-EPS och TTM-EPS behöver inte avse samma slutdatum.',
      'Läs EPS-läget i Research. Om det står Manuell, behandla talet som ditt eget antagande och dokumentera varför du valt det.', ['dilution','pe'],'research-nvda',null],
    ['fcf','FCF: fritt kassaflöde med en definition','statements','free cash flow kassaflöde capex',
      'Fritt kassaflöde försöker beskriva pengar som återstår efter investeringar i verksamheten. Det finns flera definitioner, så börja med att läsa hur måttet räknas.',
      'Vinst kan finnas samtidigt som pengar binds i lager eller kundfordringar. Kassaflödet hjälper dig att undersöka skillnaden, men ett enskilt kvartal kan påverkas av betalningarnas timing.',
      'I NTM:s enkla modell ger 120 miljoner kr i operativt kassaflöde minus 50 miljoner kr i kontanta investeringar ett FCF på 70 miljoner kr. Detta är en definition för övningen, inte ett löfte om möjlig utdelning.',
      'Kontanta investeringar kan utesluta leasing, finansierade tillgångsköp och förvärv. Aktiebaserad ersättning kan ingå som återläggning i operativt kassaflöde utan att vara kostnadsfri för ägaren. För banker kan industribolagets FCF-mått vara missvisande. NTM visar därför vissa bolags FCF som otillgängligt i stället för att tvinga fram jämförbarhet.',
      'Blanda inte två FCF-definitioner i samma tillväxtserie. Ett negativt FCF kan bero på tillväxtinvesteringar, men behöver ändå finansieras.',
      'Jämför definition och källor för FCF i Research. Skriv vilka investeringar som inte fångas innan du använder beloppet i en tes.', ['debt','marginal'],'research-crwv',null],
    ['marginal','Marginal: hur mycket blir kvar?','statements','rörelsemarginal nettomarginal bruttomarginal',
      'En marginal visar ett resultat i förhållande till intäkterna. Ange vilket resultat du använder: bruttoresultat, rörelseresultat och nettoresultat ger olika marginaler.',
      'Marginalen hjälper dig att se om högre försäljning också blir mer lönsam. Prisförändringar, produktmix och fasta kostnader kan påverka marginalen på olika sätt.',
      'Med intäkter på 200 miljoner kr och rörelseresultat på 30 miljoner kr är rörelsemarginalen 15 procent. Om intäkterna växer till 240 och resultatet till 32,4 blir marginalen 13,5 procent. Resultatet ökar trots lägre marginal.',
      'Formeln är valt resultat / intäkter × 100. En ökning från 10 till 12 procent är två procentenheter, eller 20 procent relativt den gamla marginalen. Jämför samma period och redovisningsdefinition. Nettomarginal påverkas också av finansiering och skatt, medan bruttomarginal ligger tidigare i resultaträkningen.',
      'En marginalförändring i procentenheter är inte samma sak som procentuell resultattillväxt. Marginaler är svårtolkade när nämnaren saknas eller har olämplig ekonomisk innebörd.',
      'Välj en marginal i Research och identifiera täljaren och nämnaren. Beskriv vilken kostnad som måste ändras för att din marginaltes ska hålla.', ['revenue','fcf'],'research-nvda',null],
    ['debt','Skuld: belopp, villkor och förfall','statements','nettoskuld lån balansräkning likviditet',
      'Skuld behöver bedömas både efter storlek och efter när och hur den ska betalas. Kassa kan ge handlingsutrymme men är inte alltid fritt tillgänglig.',
      'Två bolag med lika stor skuld kan ha helt olika risk om det ena måste refinansiera nästa månad och det andra har lång löptid med fast ränta.',
      'Ett fiktivt bolag har 100 miljoner kr i räntebärande lån och 30 miljoner i fritt tillgänglig kassa. Med denna avgränsning är nettoskulden 70 miljoner. Leverantörsskulder och leasing ingår inte i just den förenklade definitionen.',
      'Balansräkningen visar ett datum, medan kassaflödet täcker en period. Kontrollera förfall, ränta, säkerheter och lånevillkor i noterna. Total liabilities omfattar mer än räntebärande debt. En uppgift om långfristig skuld kan dessutom utelämna den kortfristiga delen. Banker och finansbolag kräver annan bedömning av finansieringen.',
      'Subtrahera inte all kassa utan att kontrollera restriktioner. Kalla inte en enskild skuldkomponent för total skuld.',
      'Öppna en rapportkälla i Research och leta efter skuldnoten. Anteckna nästa stora förfall och vad som skulle behöva finansieras i ett svagare scenario.', ['fcf','risk'],'research-crwv',null],
    ['dilution','Utspädning: när din andel förändras','statements','emission aktieantal stock based compensation',
      'Utspädning innebär att din relativa ägarandel minskar när fler aktier tillkommer och du inte ökar ditt innehav motsvarande. Det behöver inte betyda att värdet per aktie alltid faller.',
      'En emission kan finansiera värdeskapande investeringar eller täcka löpande förluster. Bedöm därför både hur många nya aktier som tillkommer och vad bolaget får i utbyte.',
      'Du äger tio av hundra aktier, alltså 10 procent. Bolaget ger ut tjugo nya aktier till andra ägare. Du äger nu tio av 120, cirka 8,33 procent. Om bolaget samtidigt får nytt kapital har även bolagets tillgångar förändrats.',
      'Optioner och konvertibler kan påverka framtida aktieantal. Återköp kan motverka utspädning men förbrukar pengar. Aktiebaserad ersättning är inte kontant vid samma tillfälle, men kan ändå påverka ägarens andel. Historiskt och framtida aktieantal måste därför hanteras separat i en värdering.',
      'En aktiesplit delar upp samma ägande i fler enheter och är inte i sig ekonomisk utspädning. Använd inte råa aktieantal över en split utan justering.',
      'Jämför antagen bolagsvinst med antagen EPS. Om de växer olika fort, skriv vilket aktieantal eller vilken resultatdefinition som förklarar skillnaden.', ['eps','aktier'],'tool-valuation',null],
    ['pe','P/E: pris i förhållande till vinst','valuation','price earnings p/e multipel peg',
      'P/E är aktiekursen delad med vinst per aktie. Det visar vilket pris marknaden sätter i relation till en viss vinstnivå, inte hur många år det säkert tar att få pengarna tillbaka.',
      'Samma bolag kan få olika P/E beroende på om du använder senaste årets vinst eller en framtida prognos. Skriv alltid vilken EPS och valuta som hör till priset.',
      'En kurs på 150 kr och EPS på 10 kr ger P/E 15. Om EPS senare blir 12 kr men marknaden betalar P/E 10 blir priset 120 kr. Vinsten ökade samtidigt som aktievärdet föll.',
      'Negativ eller nära noll EPS gör P/E svårtolkat. Cykliska toppvinster kan ge ett lågt tal strax före sämre tider. PEG dividerar P/E med tillväxt uttryckt i procenttal, men ett PEG kring ett är en tumregel, inte en värderingslag. Räntor, risk och kapitalbehov försvinner inte ur analysen.',
      'Lågt P/E betyder inte automatiskt billigt. Blanda inte justerad prognos-EPS med redovisad historisk EPS utan att ange skillnaden.',
      'Håll EPS-tillväxten lika och sänk slutmultipeln i värderingsverktyget. Se hur mycket av ditt utfall som beror på multipeln.', ['eps','scenarios'],'tool-valuation',null],
    ['cagr','CAGR: jämför tillväxt över flera år','valuation','årlig avkastning genomsnittlig tillväxt compound annual growth rate',
      'CAGR visar den genomsnittliga årliga tillväxttakten över en period, som om utvecklingen varit jämn varje år. Det betyder inte att investeringen faktiskt gav samma avkastning varje år.',
      'Måttet gör olika långa perioder lättare att jämföra. Det visar däremot inte hur stora svängningar du behövde tåla på vägen eller när du satte in pengar.',
      '10 000 kr blir 12 100 kr på två år utan nya insättningar. CAGR är (12 100 / 10 000)^(1/2) − 1 = 10 procent. Totalavkastningen är 21 procent, så 21 / 2 ger inte rätt årstakt.',
      'Formeln kräver ett positivt startvärde och en meningsfull slut/start-kvot. Antalet år kan vara ett decimaltal. Använd inte enkel CAGR på ett konto med löpande insättningar som om insättningarna vore avkastning. Jämför också samma valuta samt före/efter avgifter, skatt och inflation.',
      'Ett aritmetiskt medel av årsprocent är inte CAGR. En imponerande årstakt över en kort period är inte en prognos.',
      'Räkna på 10 000, 12 100 och två år i avkastningsverktyget. Prova sedan samma slutvärde efter fyra år och förklara skillnaden.', ['avkastning','compounding'],'tool-return',null],
    ['reverse','Omvänd värdering: vad kräver priset?','valuation','reverse valuation avkastningskrav required return',
      'Omvänd värdering börjar med priset och frågar vilka framtida resultat som skulle behövas för ett valt avkastningskrav. Kravet är ditt antagande, inte en utlovad avkastning.',
      'Metoden hjälper dig att skilja en lockande berättelse från vad som redan kan vara inprisat. Frågan blir om de nödvändiga antagandena är rimliga, inte om kalkylen kan ge ett exakt facit.',
      'För att 100 kr ska ge 10 procent per år i två år behövs slutvärdet 121 kr utan utdelningar. Med antaget slut-P/E 20 krävs EPS 6,05 kr. Om dagens EPS är 5 kr motsvarar det 10 procents årlig EPS-tillväxt.',
      'I den enkla modellen är framtida pris = dagens pris × (1 + avkastningskrav)^år. Dividera med slutmultipeln för erforderlig EPS. Ändrar du slutmultipeln ändras tillväxtkravet. Modellen bortser från utdelningar om de inte uttryckligen ingår och måste använda en jämförbar aktiebas.',
      'Ett högre inköpspris höjer den tillväxt som krävs för samma avkastningskrav, allt annat lika. Det gör inte den framtida vinsten mer sannolik.',
      'Höj bara inköpspriset i omvänd värdering. Anteckna vilket tillväxtkrav som följer och vad i verksamheten som skulle behöva bekräfta det.', ['pe','eps'],'tool-reverse',null],
    ['scenarios','Bear, Base och Bull','valuation','scenario känslighetsanalys prognos',
      'Scenarier beskriver flera möjliga utfall. Bear är ett svagare fall, Base ett huvudantagande och Bull ett starkare fall; inget av dem är automatiskt mest sannolikt.',
      'Använd scenarier för att se vilka antaganden värderingen är känslig för. De blir mest användbara när varje siffra har en affärsmässig förklaring.',
      'Om framtida EPS antas bli 5, 7 eller 9 kr och respektive P/E blir 12, 16 eller 20 ger modellen priserna 60, 112 och 180 kr. Alla sex indata är antaganden, inte rapporterade fakta.',
      'Skilj scenarier från sannolikheter. Ett medel av tre utfall är inte ett förväntat värde utan motiverade vikter. I ett stresstest kan tillväxt, marginal och multipel försämras samtidigt. Undvik att kombinera en mycket optimistisk tillväxt med finansieringsvillkor som bara fungerar i en annan situation.',
      'Base betyder inte säkert. Tre nästan identiska scenarier ger litet stöd för att bedöma risk. Ett exakt decimalresultat gör inte indata exakta.',
      'Bygg tre scenarier i verktyget. Skriv en konkret händelse som skulle flytta ditt huvudantagande mot det svagare fallet.', ['risk','thesis'],'tool-scenarios',null],
    ['inflation','Inflation och köpkraft','macro','KPI KPIF CPI PCE real avkastning',
      'Inflation betyder att den allmänna prisnivån stiger. När priserna ökar räcker samma antal kronor till mindre, även om saldot på kontot är oförändrat.',
      'Skilj nominell avkastning i pengar från real avkastning i köpkraft. Jämför också samma period: en årstakt och en månadsförändring beskriver olika saker.',
      'Kapitalet växer 5 procent medan priserna ökar 3 procent. Real avkastning blir 1,05 / 1,03 − 1, cirka 1,94 procent före skatt. Skillnaden 5 − 3 = 2 procent är en approximation.',
      'KPI och KPIF är svenska mått; Riksbankens mål avser KPIF. CPI och PCE är amerikanska index med olika avgränsningar och vikter. Kärnmått tar bort vissa komponenter enligt respektive definition. Fallande inflation kan fortfarande betyda stigande priser, bara i lägre takt. Den egna konsumtionskorgen kan skilja sig från index.',
      'En lägre inflationstakt betyder inte att prisnivån har gått tillbaka. Dra inte en automatisk börsslutsats från en enda datapunkt.',
      'Jämför nominellt och inflationsjusterat slutvärde i sparverktyget. Läs sedan kalenderns enhet och period för nästa inflationspublicering.', ['interest-rates','compounding'],'tool-compound','inflation'],
    ['interest-rates','Räntor och obligationspriser','macro','styrränta obligationsränta yield arbetsmarknad',
      'Ränta är priset för att låna pengar eller ersättningen för att låna ut dem. Styrränta, bolåneränta och obligationsränta är olika räntor med olika villkor.',
      'Räntor påverkar finansieringskostnader och hur framtida pengar värderas i dag. Men sambandet med aktiekurser beror också på varför räntan förändras.',
      'En framtida betalning på 110 kr om ett år är värd 100 kr vid ett avkastningskrav på 10 procent: 110 / 1,10. Vid 5 procent blir värdet cirka 104,76 kr. Framtida betalning är oförändrad; diskonteringen ändras.',
      'Priset på en befintlig obligation med fasta betalningar faller normalt när marknadens avkastningskrav stiger, allt annat lika. Längre betalningshorisont brukar öka känsligheten. Kreditrisk och löptid kan ge stora skillnader mellan obligationsräntor och styrräntan. Arbetsmarknadsdata kan påverka ränteförväntningar, men publiceringar revideras och marknaden jämför ofta mot förväntningar.',
      'En räntesänkning är inte en säker köpsignal. Kupongränta är inte samma sak som avkastningen på en obligation köpt till ett annat pris.',
      'Öppna makrokalendern och skilj ett räntebeslut från en datapublicering. Skriv vad du behöver veta om period och källa innan du tolkar utfallet.', ['inflation','reverse'],'macro-calendar','rates'],
    ['thesis','Skriv en investeringstes som går att pröva','research','investment thesis antaganden motbevis hypotes',
      'En investeringstes beskriver varför en investering kan ge ett visst utfall och vad som måste bli sant. Den skiljer observationer från dina egna antaganden.',
      'En skriven tes gör det lättare att se när du ändrar uppfattning. Den behöver inte vara lång: en affärsidé, några mätbara antaganden och tydliga motbevis räcker som start.',
      'Övning: ”Jag antar att återkommande intäkter växer minst 8 procent kommande år utan lägre rörelsemarginal.” Ett möjligt motbevis är att tillväxten kräver stora rabatter. Siffrorna är ett fiktivt antagande och ska inte föras över till ett verkligt bolag utan underlag.',
      'Skilj bolagets utveckling från aktiens pris. En bra verksamhet kan ge svag avkastning från en hög värdering. Ange källa och rapportperiod för fakta, tidshorisont för antaganden och ett granskningsdatum. Spara en ny version när tesen ändras så att tidigare resonemang kan granskas på sina egna villkor.',
      '”Aktien ska upp” är ett önskat resultat, inte en förklaring. Flytta inte målstolparna i efterhand utan att dokumentera vad som ändrats.',
      'Skapa en manuell tes i Research. Skriv ett antagande, ett motbevis och när du vill granska det. Spara först när formuleringen känns rätt för dig.', ['scenarios','report'],'workflow-manual-thesis',null],
    ['report','Följ upp en rapport utan att skriva om historien','research','kvartalsrapport TTM bokslut uppföljning resultaträkning',
      'En rapportuppföljning jämför nya observationer med vad du tidigare trodde. Börja med rapportperiod och källor innan du bedömer om tesen håller.',
      'Resultaträkning, balansräkning och kassaflöde svarar på olika frågor. Läs dem tillsammans och skilj redovisade siffror från ledningens framtidsbedömning.',
      'Du antog 8 procents omsättningstillväxt och stabil marginal. Rapporten visar 10 procents tillväxt men två procentenheter lägre marginal. Det är inte ett rent ”bättre än väntat”: dela upp observationerna och förklara vilken del av tesen som påverkas.',
      'TTM betyder de senaste fyra jämförbara kvartalen. Ett halvårsbelopp är inte ett fristående kvartal. Noter kan förklara engångsposter, periodbyte och ändrad aktiebas. Korrigerade jämförelsetal behöver behandlas som korrigeringar, inte som ny ekonomisk tillväxt. I NTM kan saknad jämförbar data blockera en automatisk jämförelse.',
      'Använd inte dagens data för att påstå att du visste samma sak när den äldre tesen skrevs. Ett bra kursutfall bevisar inte att resonemanget var bra.',
      'Öppna en sparad tesversion, granska källorna och skriv vad den nya rapporten stödjer respektive motsäger. Spara en ny version och använd Outcome separat för prisutfallet.', ['thesis','revenue'],'workflow-nvda-thesis','reports']
  ];
  rows.push(
    ['financial-statements','Läs rapportens tre perspektiv','statements','balansräkning resultaträkning kassaflödesanalys income statement balance sheet operating cash flow capex',
      'Resultaträkningen visar periodens resultat, balansräkningen visar ställningen på ett datum och kassaflödesanalysen visar hur pengarna rört sig. Läs dem tillsammans för att förstå hur resultat och pengar hänger ihop.',
      'Ett växande bolag kan redovisa vinst och ändå behöva låna. När du kan följa en affär genom rapporterna ser du om tillväxten binder pengar i kunder, lager eller anläggningar.',
      'Ett fiktivt konsultbolag börjar med 100 kr i kassa och 100 kr i eget kapital. Det fakturerar 80 kr för levererat arbete och betalar 50 kr i löner. Kunden har ännu inte betalat. Utan skatt eller andra poster blir vinsten 30 kr, men kassan faller till 50 kr. Balansen är 50 i kassa + 80 i kundfordringar = 130 i eget kapital. Operativt kassaflöde är 30 i vinst − 80 i ökade fordringar = −50 kr.',
      'När kunden betalar ökar kassan och fordran försvinner; intäkten bokas inte en gång till. Köp av en maskin är däremot normalt en investering som fördelas som avskrivning över användningstiden. Kontant CapEx och periodens avskrivning kan därför vara olika stora. Kassaflödet delas i löpande verksamhet, investering och finansiering. Ett nytt lån höjer kassan utan att vara försäljning. Noter och rapporten över eget kapital behövs också för en fullständig bild.',
      'Räkna inte en ökning av kundfordringar som ett inflöde av pengar. En stark kassa vid kvartalsslutet kan komma från nya lån; den bevisar inte att verksamheten genererar pengar. Bokfört eget kapital är inte bolagets börsvärde.',
      'Öppna årsrapporten via Research och följ tre rader: årets resultat, operativt kassaflöde och kassa vid årets slut. Skriv en förklaring till skillnaden mellan resultat och kassaflöde, med hänvisning till en faktisk not eller förändring i rörelsekapital.',
      ['revenue','fcf','debt'],'research-nvda','reports'],
    ['enterprise-value','EV och EV/EBITDA: värdera verksamheten','valuation','enterprise value företagsvärde ev/ebitda rörelsevärde',
      'Enterprise Value, EV, är ett mått på verksamhetens värde som tar hänsyn till hur den finansieras. EV/EBITDA jämför det värdet med ett resultat före ränta, skatt och avskrivningar.',
      'Börsvärdet räcker inte när du jämför två bolag med olika skuld. Ägarna i det mer skuldsatta bolaget har en mindre del av det samlade värdet, men bär en större finansiell känslighet.',
      'Bolag A har börsvärde 800 miljoner kr, räntebärande skuld 300 och kassa 100. I den förenklade modellen är EV = 800 + 300 − 100 = 1 000. Med EBITDA 100 blir EV/EBITDA 10. Bolag B har börsvärde 1 000, ingen skuld eller kassa och samma EBITDA. Båda får multipeln 10 trots olika börsvärde.',
      'För ett verkligt bolag kan bryggan även behöva preferenskapital, minoritetsintressen och konsekvent behandling av leasing. EBITDA återlägger avskrivningar men betalar varken investeringar, ränta eller skatt. Ett bolag med stora återkommande investeringar kan därför se billigt ut på EBITDA och ändå ha litet kassaflöde. Kontrollera avstämningen för justerad EBITDA; återkommande kostnader försvinner inte ekonomiskt för att de exkluderas. Måttet passar sämre för banker där finansieringen är del av verksamheten.',
      'Jämför inte EV med ett resultat efter räntekostnader som om täljare och nämnare gällde samma kapitalägare. Blanda inte bolag som behandlar leasing olika. En låg multipel är en fråga att undersöka, inte ett köpargument i sig.',
      'Använd rapportkällan i Research för en egen EV-brygga på papper: börsvärde, skuld, kassa och eventuella justeringar. NTM:s P/E-kalkyl är ingen EV-kalkyl; mata inte in EBITDA i EPS-fältet. Jämför sedan vilket kapitalbehov som EBITDA missar.',
      ['aktier','debt','fcf','pe'],'research-crwv','reports'],
    ['forward-metrics','Historik, prognos och konsensus','valuation','forward trailing TTM guidance prognos analytiker estimates consensus estimat',
      'Trailing beskriver historiska resultat och forward använder framtida bedömningar. Guidance är bolagsledningens prognos eller intervall; konsensus sammanfattar ett urval analytikers estimat.',
      'Ett nyckeltal kan se lägre ut enbart för att nämnaren bygger på en optimistisk framtid. Du behöver veta vem som gjort prognosen, när den uppdaterades och vilket räkenskapsår den avser.',
      'Kursen är 120 kr. Rapporterad EPS för senaste tolv månaderna är 4 kr, så trailing P/E är 30. Med prognos-EPS 6 kr blir forward P/E 20. Priset har inte ändrats; skillnaden är antagandet om vinsten. Sänks prognosen till 5 kr stiger forward P/E till 24 även om kursen står stilla.',
      'Nästa räkenskapsår och kommande tolv månader är olika perioder. Ett konsensusmedel kan dölja stor spridning, få analytiker eller gamla estimat. Median och medel behöver inte vara lika. Ledningens guidance kan avse justerade mått eller konstant valuta och ska då jämföras på samma grund. Ett utfall över konsensus kan samtidigt understiga din egen tes. Vid rapportdagen behöver du skilja nytt utfall, prognosändring och marknadens prisreaktion.',
      'Kalla inte ett eget antagande för konsensus. Jämför inte redovisad EPS med justerad prognos-EPS utan avstämning. Att prognosen är exakt formaterad med två decimaler betyder inte att osäkerheten är liten. Spara prognosen som den såg ut vid beslutet, så att senare revideringar inte ersätter ditt ursprungliga underlag.',
      'Skriv period, definition, källa och datum bredvid ditt EPS-antagande i Research. Om du inte har ett verifierat konsensusunderlag, märk det som eget antagande. Spara en tesversion före rapporten och jämför den med utfallet efteråt.',
      ['eps','pe','report'],'workflow-manual-thesis','reports'],
    ['position-sizing','Positionsstorlek, tid och möjliga förluster','start','position sizing drawdown nedgång återhämtning risk/reward placeringshorisont',
      'Positionsstorlek är hur stor del av kapitalet ett innehav får utgöra. Den avgör hur mycket en enskild investering kan påverka din ekonomi, tillsammans med risken i resten av portföljen.',
      'En lovande tes kan ändå vara för stor för ditt sparmål. Börja med vilka pengar som behöver vara tillgängliga och vilken förlust du kan bära utan att tvingas sälja andra tillgångar.',
      'Ett innehav på 20 000 kr i en portfölj på 100 000 kr väger 20 procent. Om innehavet halveras och resten står stilla förlorar portföljen 10 procent. Själva innehavet måste sedan stiga 100 procent för att återhämta ett fall på 50 procent: 1 / (1 − 0,50) − 1 = 1.',
      'I en förenklad stoppmodell kan antal aktier beräknas som vald riskbudget / (köpkurs − stoppnivå). Med 1 000 kr i riskbudget, kurs 100 och stopp 90 blir det 100 aktier före avgifter. Det är ingen maximal möjlig förlust: kursgap, brist på köpare och belåning kan ge ett sämre utfall. Drawdown mäter fallet från en tidigare topp till en senare botten. Det säger varken hur lång återhämtningen blir eller om den alls sker. Risk/reward utan sannolikheter beskriver bara möjliga belopp.',
      'En stopporder garanterar inte sitt pris. Två stora innehav med samma riskdrivare kan falla samtidigt. Räkna inte en procentuell återhämtning från det ursprungliga toppvärdet; basen är det lägre värdet efter fallet.',
      'Öppna aktieköpsverktygets läge Positionsstorlek. Pröva en egen riskbudget och kontrollera sedan ett separat scenario där stoppet inte kan utföras. Skriv också när pengarna behövs och hur innehavet samvarierar med resten av ditt tänkta sparande.',
      ['risk','diversifiering','thesis'],'tool-purchase','risk']
  );
  // Each extension adds a distinct worked comparison and interpretation, not filler.
  const depth={
    aktier:['Jämför två priser','Bolag A har kurs 10 kr och 100 miljoner aktier: börsvärdet är en miljard. Bolag B har kurs 1 000 kr och 100 000 aktier: börsvärdet är 100 miljoner. Den billigare aktien i kronor tillhör alltså det större bolaget. Vid olika aktieslag behöver varje klass värderas på sin egen grund.','En utdelning på 2 kr från en aktie kring 100 kr flyttar pengar från bolaget till ägaren. Allt annat lika minskar värdet som är kvar i bolaget. Marknadsrörelser kan dölja detta på utdelningsdagen. Fråga om utdelningen täcks av uthålliga kassaflöden eller av lån.'],
    fonder:['Läs vad fonden jämförs med','En fond som stigit 8 procent kan ha gått sämre än ett jämförbart totalavkastningsindex som stigit 10 procent. En annan fond med 5 procent kan ha haft helt annan risk. Jämförelsen blir användbar först när period, valuta och utdelningar behandlas lika.','Ett marknadsviktat index ger större bolag större vikt. Det är en regel, inte en bedömning av vilka bolag som är billigast. Kontrollera de största innehaven och om fondens mandat tillåter koncentration eller derivat. Tidigare avkastning efter avgifter säger inte vilken fond som kommer att vinna.'],
    etf:['Skilj orderkurs från underliggande värde','Om andelens uppskattade nettovärde är 100 kr och du betalar 101 kr köper du med en premie på 1 procent. Premien kan försvinna utan att innehaven faller. I spreadexemplet ovan avser köpkurs priset du som sparare betalar och säljkurs det du får.','Fysisk replikering äger normalt alla eller ett urval av indexets värdepapper; syntetisk replikering använder avtal för exponeringen. Läs därför motparts- och säkerhetsvillkor. Handel när den underliggande marknaden är stängd kan ge större prisosäkerhet. En limitorder begränsar priset men garanterar inte att affären blir av.'],
    avkastning:['Skilj utdelning från nytt sparande','Om du börjar med 10 000 kr, sätter in 5 000 kr precis vid periodens slut och saldot då är 15 200 kr är vinsten 200 kr i denna förenklade situation. Att dividera 15 200 med 10 000 skulle felaktigt räkna insättningen som avkastning.','Tidsviktad avkastning länkar delperioder kring kassaflöden och används för att jämföra förvaltning. Pengaviktad avkastning påverkas av när du själv satt in pengar. Vilket mått som besvarar frågan beror därför på om du jämför en strategi eller ditt personliga sparutfall.'],
    risk:['Pröva både fall och väntetid','Ett värdefall från 100 till 50 kräver en fördubbling för återhämtning. Men även en oförändrad kurs i fem år kan vara ett dåligt utfall om du behöver pengarna efter två år eller köpkraften urholkas. Skriv därför både ett förlustbelopp och ett behovsdatum.','Skilj bolagsrisk, prisrisk och din egen finansiering. En stabil verksamhet kan ha en högt värderad aktie. En obelånad investering kan vara fel för en kort utgiftshorisont. Risk/reward anger möjliga belopp; utan motiverade sannolikheter säger kvoten inte om affären är attraktiv.'],
    diversifiering:['Räkna på överlappet','Du placerar hälften i en fond med 40 procent teknik och hälften i en teknikfond med 100 procent teknik. Den sammanlagda teknikvikten blir 0,5 × 40 + 0,5 × 100 = 70 procent. Två fondnamn har inte gett två oberoende exponeringar.','En riskkarta kan därför gruppera innehav efter drivare i stället för bransch. Samma ränteuppgång kan påverka högt värderad tillväxt, fastigheter och belånade hushåll. Sambanden varierar; använd kartan som en fråga att testa, inte som en exakt prognos för korrelation.'],
    compounding:['Skilj insats från tillväxt','Med 1 000 kr från start och ytterligare 1 000 kr i slutet av första året blir kapitalet 2 050 kr vid antagna 5 procent. Efter nästa år är det 2 152,50 kr utan fler insättningar. Av detta är 2 000 kr dina egna pengar.','Insättning i början av perioden får längre tid att växa än insättning i slutet. Jämför därför inte två kalkyler förrän tidpunkten är lika. Vid uttag blir ordningen på goda och dåliga år betydelsefull: ett tidigt fall lämnar mindre kapital kvar efter samma uttag.'],
    fees:['Räkna på avgiftens underlag','Om 100 kr först växer 7 procent och därefter belastas med 1 procent av det nya värdet återstår 100 × 1,07 × 0,99 = 105,93 kr. En modell som subtraherar en procentenhet ger 106 kr. Skillnaden kommer från när och på vilket underlag avgiften tas.','NTM:s jämförelse isolerar en vald kostnadsmodell. För en verklig produkt behöver faktablad, prislista och valutaomräkning stämma med dina affärer. Anteckna separat löpande procentavgift, kostnad per order och spread; annars kan ett billigt långsiktigt alternativ se dyrt ut vid täta små köp, eller tvärtom.'],
    gav:['Vikta olika stora köp','Tio aktier à 100 kr och trettio à 80 kr ger (1 000 + 2 400) / 40 = 85 kr. Medelvärdet av orderpriserna, 90 kr, är fel eftersom du köpt olika många. Ange tidigare GAV inklusive tidigare kostnader och lägg bara till det nya köpets kostnader.','Efter en split två mot en halveras GAV och antalet fördubblas, medan total kostnadsbas är oförändrad. Försäljningar och bolagshändelser kräver samma enhetliga underlag. Separera bokföringen av vad du betalade från frågan vad du skulle vara beredd att betala i dag.'],
    isk:['Förstå underlaget innan du väljer år','Ett enkelt principfall utan insättningar har kvartalsvärden 80 000, 100 000, 100 000 och 120 000 kr. Medelvärdet är 100 000 kr. Ett slutvärde på 120 000 kr beskriver alltså inte ensamt kapitalunderlaget. Vid insättningar och överföringar måste årets särskilda regler användas.','Skatteverkets vägledning skiljer kapitalunderlag, schablonintäkt och slutlig skatteeffekt. Räkna inte en skattefri grundnivå en gång för varje konto eller institut. Utländsk källskatt och överföring från vanlig depå kan kräva ytterligare kontroll; principövningen här avgör inte sådana fall.'],
    currency:['Testa ett till synes neutralt utfall','Aktien stiger 10 procent i USD och dollarn faller 10 procent mätt i SEK per USD. Då blir 1,10 × 0,90 − 1 = −1 procent. Lika stora procenttal med olika tecken tar inte ut varandra eftersom valutaförändringen även träffar aktiens värdeökning.','Om du i stället anger USD per SEK måste förändringen vändas genom kvoten, inte bara byta tecken. Kontanta utdelningar som växlas på olika datum behöver egna valutakurser. NTM:s enkla FX-övning passar ett start- och slutvärde utan mellanliggande kassaflöden.'],
    revenue:['Skilj organisk tillväxt från förvärv','Intäkterna går från 100 till 130 miljoner. Om ett nyköpt bolag bidrar med 25 miljoner är den återstående ökningen fem miljoner i denna förenklade övning med oförändrad valuta. Den rapporterade ökningen på 30 procent säger därför inte att den gamla verksamheten växte lika snabbt.','Intäktsredovisning beror på vad som levererats och vilka prestationsåtaganden som återstår. En kunds förskottsbetalning kan först vara en skuld till kunden. Ordervärde, bokningar och omsättning är olika mått. Följ definitionerna över tid innan du gör en tillväxtserie eller jämför konkurrenter.'],
    eps:['Skilj tidsvägning från slutantal','Ett bolag har två miljoner aktier under första halvåret och tre miljoner under andra. Utan andra förändringar blir vägt årsgenomsnitt 2,5 miljoner. Med 10 miljoner kr i relevant årsresultat blir grundläggande EPS 4 kr, inte 3,33 kr som med enbart slutantalet.','Utspädd EPS är en redovisningsberäkning, inte ett godtyckligt maximalt aktieantal. Instrument som skulle förbättra EPS genom antagen utspädning behandlas enligt regler om anti-utspädning. Läs notens avstämning och skilj IFRS från US GAAP där detaljerna avviker. En prognos måste dessutom ha en egen framtida aktiebas.'],
    fcf:['Följ rörelsekapitalet','Anta vinst 100, avskrivningar 20 och en ökning av kundfordringar med 40, utan andra justeringar. Operativt kassaflöde blir 80. Med kontant CapEx 30 återstår 50 i vår FCF-definition. Vinst på 100 betyder alltså inte att 100 finns till utdelning.','CapEx är investeringar i tillgångar; det är inte samma sak som periodens avskrivning. Uppdelningen i underhåll och tillväxt kan vara en analytikers bedömning snarare än en rapporterad sanning. Granska även förvärv och leasing vid sidan av måttet. En svag kassakonvertering under ett kvartal behöver följas över en längre jämförbar period.'],
    marginal:['Följ resultatet genom kostnadslagren','Vid intäkter 200 och kostnad för sålda varor 120 blir bruttoresultatet 80 och bruttomarginalen 40 procent. Övriga rörelsekostnader på 50 lämnar rörelseresultat 30 och rörelsemarginal 15 procent. Ränta och skatt påverkar sedan nettoresultatet, inte denna rörelsemarginal.','Hur kostnader grupperas beror på bransch och rapportformat. Hög bruttomarginal kan behövas för att finansiera forskning eller försäljning. En förbättring genom tillfälliga nedskärningar är inte samma sak som uthållig prissättningskraft. Läs därför både förändringen och kostnaderna bakom den.'],
    debt:['Testa räntetäckningen','Ett bolag har rörelseresultat 30 och räntekostnad 10. I modellen EBIT / räntekostnad är täckningen tre gånger. Om resultatet halveras och räntan stiger till 15 blir den en gång. Samma lånebelopp kan alltså bli betydligt tyngre att bära.','Räntetäckning är inte ett fullständigt likviditetstest: amortering, investeringar och rörelsekapital kräver också pengar. Nettoskuld kan dölja att kassan finns i en annan del av koncernen. Kontrollera också om ett lånevillkor använder en justerad resultatdefinition som skiljer sig från ditt eget mått.'],
    dilution:['Skilj återköpt belopp från faktisk aktieminskning','Med vinst 100 och 100 aktier är EPS 1. Om bolaget återköper tio aktier och vinsten förblir 100 blir förenklad framtida EPS 100 / 90 ≈ 1,11. Men återköpet förbrukar kassa; antagandet om oförändrad vinst bortser från förlorad ränteintäkt eller ny räntekostnad.','Ett stort återköpsprogram kan samtidigt kompenseras av aktiebaserad ersättning. Följ därför faktisk aktiebas och nettokostnad över tid. Återköp långt över ett rimligt värde kan förstöra värde trots högre EPS. Högre resultat per aktie är inte ensamt ett bevis på ett bra kapitalbeslut.'],
    pe:['Pröva PEG med rätt enhet','P/E 20 och antagen årlig vinsttillväxt 10 procent ger PEG 20 / 10 = 2, inte 20 / 0,10 = 200. Vid noll eller negativ tillväxt blir tumregeln olämplig. Två bolag med samma PEG kan ha olika skuld, lönsamhet och kapitalbehov.','Ett multipelval sammanfattar många antaganden. Högre uthållig tillväxt kan motivera ett annat pris, men bara om den skapar värde efter investeringarna som behövs. Jämför samma vinstperiod och definition, pröva en lägre slutmultipel och skriv vad som skulle göra din jämförelse missvisande.'],
    cagr:['Jämför medelvärde med faktisk tillväxt','Två år med +50 och −50 procent ger 100 × 1,50 × 0,50 = 75. Det aritmetiska medlet är noll, men CAGR är √0,75 − 1 ≈ −13,4 procent. Ordningen ändrar inte slutvärdet i detta exempel utan insättningar eller uttag.','Noll i slutvärde motsvarar total förlust och kräver tydlig hantering i verktyget; negativa ekonomiska start- eller slutvärden passar inte vanlig CAGR-tolkning. Årlig tillväxt i omsättning och årlig avkastning för ägaren använder liknande matematik men beskriver olika saker. Blanda inte bolagets tillväxt med din avkastning.'],
    reverse:['Håll avkastningskrav och slutmultipel isär','Med pris 100, två år och avkastningskrav 10 procent behövs fortfarande 121 i slutpris. Sänks slut-P/E från 20 till 15 ökar nödvändig EPS från 6,05 till cirka 8,07. Från EPS 5 krävs då cirka 27 procent årlig tillväxt, utan utdelningar.','Översätt den tillväxten till verksamheten: fler kunder, högre marginal eller färre aktier? Om flera antaganden måste lyckas samtidigt är prisets krav större än en enda tillväxtsiffra visar. Omvänd värdering identifierar vad som krävs; den uppskattar inte automatiskt sannolikheten att det sker.'],
    scenarios:['Skilj känslighet från ett sammanhängande scenario','Vid EPS 7 ger P/E 12, 16 och 20 priserna 84, 112 och 140. Det isolerar multipelns effekt. Ett riktigt Bear-scenario kan även ha lägre EPS, sämre finansiering och högre utspädning, vilket gör utfallet mer än en multipeljustering.','Om du väljer sannolikheter måste de summera till 100 procent och ha en motivering. Ett viktat framtida pris är ändå inte samma sak som riskfri avkastning eller lämplig positionsstorlek. Skriv vilken observation som skulle ändra vikterna och granska den vid nästa rapport.'],
    inflation:['Skilj prisnivå, årstakt och bas','Ett prisindex går från 100 till 110 och sedan till 112,2. Inflationen faller från 10 till 2 procent, men priserna ligger 12,2 procent över startnivån. En hög jämförelsebas kan sänka årstakten även när senaste månadens prisökning är tydlig.','KPIF håller hushållens bolåneräntor konstanta i beräkningen. Amerikanska CPI och PCE skiljer sig bland annat i täckning, vikter och formel; använd publicerarens definition. Jämför inte ett säsongsrensat månadsutfall med ett ospecificerat årstal. Kärninflation är ett analysmått, inte ett mått på vad varje hushåll faktiskt betalar.'],
    'interest-rates':['Läs avkastningskurvan','Avkastningskurvan visar räntor för jämförbara obligationer med olika löptid vid samma tidpunkt. Om tvåårsräntan är 4 procent och tioårsräntan 3 procent lutar denna del nedåt. Det är en prisbild, inte ett datum för nästa lågkonjunktur.','Räntan kan innehålla både förväntningar om korta räntor och ersättning för löptidsrisk. Kreditrisk måste hållas jämförbar. Arbetslöshet mäter en andel av arbetskraften och säger inte ensamt hur sysselsättningen förändrats; deltagande och revideringar kan ändra tolkningen. Läs flera publiceringar innan du ändrar en långsiktig tes.'],
    thesis:['Gör motbeviset observerbart','”Bra ledning” är svårt att pröva. En tydligare hypotes är att en ny produkt ska nå positiv bruttomarginal inom fyra kvartal utan att kundbortfallet ökar. Skriv vilket rapportmått som kan stödja detta och vad du gör om bolaget slutar redovisa måttet.','Ett motbevis behöver inte utlösa en automatisk försäljning, men bör utlösa en dokumenterad omprövning. Skilj fel data, fel affärsantagande och för högt inköpspris. Då kan du lära av ett bra eller dåligt utfall utan att tillskriva allting skicklighet eller otur.'],
    report:['Behåll jämförelsen som den faktiskt såg ut','Inför rapporten noterade du EPS 5 som eget antagande för helåret. Kvartals-EPS 1,20 kan inte direkt jämföras med det talet. Kontrollera återstående period, säsong, justeringar och aktiebas innan du uppdaterar helårsbilden. Spara också vilket datum underlaget blev känt.','Ledningens nya guidance är ett framåtblickande påstående, medan kvartalets kassaflöde är ett historiskt utfall. Dela upp uppföljningen i observation, påverkan på tesen och nästa kontrollpunkt. En kursreaktion kan handla om förväntningar som skiljer sig från dina; den ersätter inte läsningen av rapporten.']
  };
  const checks={
    risk:{question:'100 kr faller 10 % och stiger sedan 10 %. Vad återstår?',options:['99 kr','100 kr','101 kr'],answer:0,explanation:'90 × 1,10 = 99. Procenten räknas på ett nytt underlag efter nedgången.'},
    cagr:{question:'10 000 kr blir 12 100 kr på två år utan insättningar. CAGR?',options:['10 %','10,5 %','21 %'],answer:0,explanation:'1,10 × 1,10 = 1,21. Årstakten är 10 %, totalavkastningen 21 %.'},
    reverse:{question:'Priset stiger, men slutvärde och tid är oförändrade. Vad händer med möjlig årsavkastning?',options:['Den minskar','Den ökar','Den är oförändrad'],answer:0,explanation:'Du betalar mer för samma framtida belopp. För att behålla samma avkastningskrav måste det framtida utfallet i stället bli högre.'},
    eps:{question:'Resultatet är oförändrat men jämförbart aktieantal ökar. Vad händer med EPS i den enkla modellen?',options:['EPS minskar','EPS ökar','EPS är alltid oförändrad'],answer:0,explanation:'Samma resultat fördelas på fler aktier. Verklig utspädd EPS kräver även kontroll av redovisningsreglerna.'},
    currency:{question:'Aktien +10 % i USD, USD −5 % i SEK. Utfallet i SEK?',options:['4,5 %','5 %','15 %'],answer:0,explanation:'1,10 × 0,95 − 1 = 0,045. Förändringarna multipliceras.'}
  };
  Object.assign(checks,{
    pe:{question:'Kurs 100 kr och jämförbar EPS 5 kr. Vilket P/E?',options:['5','20','50'],answer:1,explanation:'100 / 5 = 20. Använd samma valuta och ange vilken period EPS gäller.'},
    'position-sizing':{question:'Efter ett fall på 50 %, vilken uppgång krävs för återhämtning?',options:['50 %','75 %','100 %'],answer:2,explanation:'100 blir 50. För att 50 ska bli 100 måste värdet fördubblas, alltså stiga 100 %.'},
    'financial-statements':{question:'Kunden betalar en redan redovisad fordran. Vad händer i det enkla exemplet?',options:['Ny intäkt uppstår','Kassan ökar och fordran minskar','Vinsten fördubblas'],answer:1,explanation:'Intäkten redovisades när arbetet levererades. Betalningen flyttar värde från kundfordran till kassa.'},
    'enterprise-value':{question:'Börsvärde 800, skuld 300, kassa 100. Förenklat EV?',options:['600','800','1 000'],answer:2,explanation:'800 + 300 − 100 = 1 000. Verkliga bolag kan kräva fler justeringar och en konsekvent leasingdefinition.'},
    'forward-metrics':{question:'Oförändrad kurs, men lägre prognos-EPS. Forward P/E?',options:['Ökar','Minskar','Ändras inte'],answer:0,explanation:'Priset divideras med en mindre vinstprognos. Multipeln stiger trots att aktiekursen står stilla.'},
    gav:{question:'10 aktier à 100 och 30 à 80, utan avgifter. GAV?',options:['90 kr','85 kr','80 kr'],answer:1,explanation:'(10 × 100 + 30 × 80) / 40 = 85 kr. De större köpen väger mer.'}
  });
  const lessons=rows.map(([id,title,category,aliases,summary,why,example,deep,mistake,exercise,relatedConcepts,tool,source],order)=>({
    id,slug:id,title,category,aliases:aliases.split(' '),difficulty:['valuation','statements','research'].includes(category)?'intermediate':'beginner',
    summary,sections:{why,example,deep,mistake,exercise},extension:depth[id]?{title:depth[id][0],example:depth[id][1],interpretation:depth[id][2]}:null,relatedConcepts,relatedEntityIds:[tool],order,status:'published',
    references:source?[{title:sources[source][0],url:sources[source][1],reviewedAt:'2026-09-15'}]:[],
    method:'NTM:s egen pedagogiska förklaring och förenklade räkneexempel. Exempel är inte prognoser eller personliga råd.',
    ...(id==='isk'?{ruleId:'isk'}:{}),quiz:checks[id]?[checks[id]]:[]
  }));
  const paths=[
    {id:'beginner',title:'Jag är helt ny',lessons:['aktier','fonder','risk','diversifiering','compounding','fees','isk']},
    {id:'analysis',title:'Jag vill analysera aktier',lessons:['revenue','marginal','eps','fcf','debt','dilution','thesis','report']},
    {id:'valuation',title:'Jag vill förstå värdering',lessons:['avkastning','cagr','eps','pe','reverse','scenarios']},
    {id:'macro',title:'Jag vill förstå makro',lessons:['inflation','interest-rates','currency','risk']}
  ];
  const journeys={
    beginner:{goal:'Förstå vad du äger, vad sparandet kostar och vilken risk du kan bära.',endpoint:'Jämför ett enkelt sparande med egna antaganden.',entity:'tool-compound',nextPath:'analysis'},
    analysis:{goal:'Koppla försäljning och vinst per aktie till finansiering och en prövbar tes.',endpoint:'Skriv och spara en egen bolagstes i Research.',entity:'workflow-manual-thesis',nextPath:'valuation'},
    valuation:{goal:'Skilj historik från prognos och undersök vad dagens pris kräver.',endpoint:'Pröva ett lägre och ett högre värderingsscenario.',entity:'tool-scenarios',nextPath:'thesis'},
    macro:{goal:'Tolka inflation, räntor och valuta utan att göra en datapunkt till en handelssignal.',endpoint:'Läs en publicerings period, enhet och källa i makrokalendern.',entity:'macro-calendar',nextPath:'beginner'}
  };
  paths.forEach(p=>Object.assign(p,journeys[p.id]));
  paths.find(p=>p.id==='valuation').lessons=['avkastning','cagr','eps','pe','forward-metrics','enterprise-value','reverse','scenarios'];
  paths.push(
    {id:'reports',title:'Jag vill förstå finansiella rapporter',goal:'Följ en affär från intäkt till resultat, balans och pengar.',lessons:['financial-statements','revenue','marginal','fcf','debt','eps','report'],endpoint:'Följ tre rapportrader till originalkällan i Research.',entity:'research-nvda',nextPath:'analysis'},
    {id:'thesis',title:'Jag vill bygga en investeringstes',goal:'Skriv antaganden som går att pröva och planera omprövningen.',lessons:['thesis','forward-metrics','scenarios','position-sizing','report'],endpoint:'Spara en tes med motbevis och nästa kontrollpunkt.',entity:'workflow-manual-thesis',nextPath:'reports'}
  );
  const descriptions={start:['Förstå ägande och risk','Lär dig skilja pris, innehåll och möjliga förluster innan du väljer investering.'],saving:['Få kontroll på sparandets villkor','Se hur tid, kostnader, kontotyp och valuta påverkar det som blir kvar.'],statements:['Läs bolagets ekonomi','Koppla intäkter, resultat, aktieantal och pengar så att ett nyckeltal får sammanhang.'],valuation:['Undersök vad priset kräver','Skilj fakta från prognoser och pröva hur ändrade antaganden påverkar värdet.'],macro:['Förstå ekonomin runt bolaget','Läs inflation, räntor och valuta med rätt period och rimliga begränsningar.'],research:['Gör analysen möjlig att följa upp','Formulera en tes, dokumentera motbevis och jämför nästa rapport med det du trodde.']};
  categories.forEach(c=>{[c.goal,c.description]=descriptions[c.id];});
  const extraAliases={aktier:['börsvärde','market cap','utdelning'],fees:['mäklaravgift'],cagr:['snittavkastning'],pe:['pris/vinst'],fcf:['fritt kassaflöde'],dilution:['återköp','buybacks']};
  const reference=(title,url)=>({title,url,reviewedAt:'2026-09-15'});
  const accounting=reference(...sources.reports);
  const epsSource=reference('IFRS: IAS 33, EPS och vägt aktieantal','https://www.ifrs.org/issued-standards/list-of-standards/ias-33-earnings-per-share/');
  const cashSource=reference('IFRS: IAS 7, kassaflödesanalys','https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/');
  const adjustedSource=reference('SEC: definition och avstämning av alternativa resultatmått','https://www.sec.gov/rules-regulations/staff-guidance/corporation-finance-interpretations/non-gaap-financial-measures');
  lessons.forEach(l=>{
    l.aliases.push(...(extraAliases[l.id]||[]));
    if(l.category==='statements'&&!l.references.some(r=>r.url===accounting.url))l.references.push(accounting);
    if(['eps','dilution'].includes(l.id))l.references.push(epsSource);
    if(['fcf','financial-statements'].includes(l.id))l.references.push(cashSource);
    if(['enterprise-value','forward-metrics','pe'].includes(l.id))l.references.push(adjustedSource);
    if(['enterprise-value','reverse'].includes(l.id))l.difficulty='advanced';
    l.reviewedAt='2026-09-15';
  });
  lessons.find(l=>l.id==='interest-rates').references.push(reference('BLS: arbetskraft och arbetslöshet','https://www.bls.gov/cps/definitions.htm'));
  lessons.find(l=>l.id==='revenue').references.push(reference('IFRS: IFRS 15, intäkter från kundavtal','https://www.ifrs.org/issued-standards/list-of-standards/ifrs-15-revenue-from-contracts-with-customers/'));
  lessons.find(l=>l.id==='etf').references.push(reference('ESMA: information om fysisk och syntetisk replikering','https://www.esma.europa.eu/publications-data/questions-answers/1103'));
  lessons.find(l=>l.id==='financial-statements').order=10.5;
  lessons.find(l=>l.id==='position-sizing').order=5.5;
  lessons.find(l=>l.id==='inflation').references.push(
    {title:'BLS: konsumentprisindex CPI',url:'https://www.bls.gov/cpi/questions-and-answers.htm',reviewedAt:'2026-09-15'},
    {title:'BEA: skillnader mellan PCE och CPI',url:'https://www.bea.gov/help/faq/555',reviewedAt:'2026-09-15'}
  );
  const published=()=>lessons.filter(l=>l.status==='published').sort((a,b)=>a.order-b.order);
  const url=id=>{const l=published().find(l=>l.id===id);return l?'academy-'+l.slug+'.html':null;};
  const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function search(text='',category=''){const terms=normalize(text).trim().split(/\s+/);return published().filter(l=>(!category||l.category===category)&&terms.every(t=>normalize([l.title,l.summary,...l.aliases,...l.relatedConcepts,categories.find(c=>c.id===l.category).title].join(' ')).includes(t)));}
  function journey(id,states){const p=paths.find(p=>p.id===id);if(!p)return null;const ids=p.lessons.filter(id=>url(id));const done=ids.filter(id=>states.get(id)?.status==='complete').length;return {done,total:ids.length,complete:done===ids.length,next:ids.find(id=>states.get(id)?.status!=='complete')||null};}
  const api={version:2,categories,lessons,paths,published,url,search,journey};
  root.NTMAcademyCatalog=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
