const NTM_POSTS = [
  {
    "title": "Jordi Visser om exponentiell AI, trading och makro",
    "date": "2026-09-13",
    "slug": "jordi-visser-linjart-exponentiellt-ai-trading",
    "category": "Video",
    "tags": [
      "AI",
      "Crypto",
      "Makro",
      "Trading",
      "Tokenisering",
      "Robinhood"
    ],
    "excerpt": "AI-sammanfattning av Jordi Vissers resonemang om exponentiell AI, digital arbetskraft, trading och makro. Sammanfattning och slutsatser på svenska och engelska.",
    "media": {
      "type": "youtube",
      "videoId": "VPuzUZlvk0U",
      "externalUrl": "https://www.youtube.com/watch?v=VPuzUZlvk0U"
    },
    "content": "<p><strong>Källa:</strong> Jordi Visser. Originalvideo: <span lang=\"en\">Linear vs. Exponential: AGI Has Arrived But Oil, Bonds and the Fed Oh My</span>.</p><p>Sammanfattningen återger Vissers argument och prognoser, inklusive hans påstående om AGI. De är inte NTM:s faktapåståenden. Se originalvideon via YouTube-länken nedan.</p>",
    "summary": {
      "sv": [
        "Jordi Visser fortsätter sin tes om linjärt kontra exponentiellt tänkande. Hans huvudargument är att investerare fortfarande lägger för mycket fokus på klassiska makrofaktorer som oljepris, obligationsräntor och Fed, samtidigt som den betydligt större förändringen sker inom AI, digital arbetskraft och exponentiell produktivitet.",
        "Visser menar att ekonomin förändrats strukturellt sedan finanskrisen. Tidigare var tillväxten mer beroende av räntekänsliga delar som bostäder och bilar. I dag ser han AI-capex, digitala affärsmodeller och teknologisk produktivitet som viktigare drivkrafter. Därför anser han att marknaden ofta överreagerar på små förändringar i räntor, inflation och oljepris.",
        "En central del av videon är hans påstående att AGI i praktiken har anlänt genom nästa generation av AI-system och agentfunktioner. Han lyfter särskilt fram Astra och utvecklingen mot modeller som kombinerar chat, agenter, kod, desktopfunktioner och andra verktyg i samma system.",
        "Visser fokuserar mycket på hur AI-agenter kan skapa en ny typ av digital arbetskraft. I den gamla ekonomiska modellen begränsades tillväxt av antalet människor, kapital och mänsklig produktivitet. I den nya modellen kan tusentals AI-agenter arbeta parallellt, vilket enligt honom gör compute, energi och tillgång till intelligens till allt viktigare begränsningar.",
        "Han använder AI:s arbete med Navier–Stokes-problemet som exempel på varför detta kan få större konsekvenser än bara effektivare kontorsarbete. Om AI kan accelerera vetenskapliga genombrott inom exempelvis energi, tillverkning, transport, medicin och fysik kan den långsiktiga ekonomiska potentialen öka samtidigt som vissa befintliga bolags konkurrensfördelar försvagas snabbare.",
        "Det leder till hans resonemang kring terminalvärde och värderingsmultiplar. Visser tror att AI kan förkorta livslängden på många företags konkurrensfördelar. Ett bolag som ser starkt ut i dag kan snabbare bli disruptat. Samtidigt kan vinnarna växa mycket snabbare. Därför tror han att traditionella värderingsmodeller kan bli mindre användbara i en exponentiell ekonomi.",
        "En stor del av videon handlar även om praktisk användning av AI. Visser beskriver hur han själv använder AI-agenter för att bygga och backtesta tradingmodeller utan att behöva kunna programmera på traditionellt sätt. Han ser AI som ett verktyg som kan ge individer större agency — möjligheten att själv bygga produkter, strategier och företag.",
        "Hans tradingmodell bygger på att först definiera ett universum av strukturella vinnare, exempelvis bolag som gynnas av AI-infrastruktur, och därefter använda faktorer som trend, rate of change, ATR, reset-faser och breakout-signaler för att hitta bättre entries och exits. Poängen är dock mindre själva modellen och mer att AI nu gör det möjligt för en individ att skapa, testa och förkasta tusentals idéer mycket snabbare.",
        "Visser tror därför att framtidens trading i allt högre grad blir agentbaserad. Han lyfter Robinhood, Moomoo och Interactive Brokers som plattformar där användare kan kombinera strategier, data och automatisering. Målet blir inte att hitta en perfekt modell, utan att skapa flera okorrelerade strategier och kontinuerligt testa nya idéer.",
        "På AI-infrastruktursidan argumenterar han för att efterfrågan på compute fortfarande är extremt stark. Han pekar särskilt på att äldre Nvidia H100-GPU:er enligt de siffror han diskuterar har behållit sitt ekonomiska värde bättre än många skeptiker förväntade sig. Om compute-priser och GPU-utilisering förblir höga kan hyperscalers enligt honom generera betydligt mer kassaflöde från redan installerad kapacitet.",
        "Han tar samtidigt upp riskerna. AI-utvecklingen innebär större cybersecurity-, privacy- och trustproblem. Han hänvisar till cyberattacker, AI-assisterad hacking och attacker mot kritisk infrastruktur som exempel på att tekniken även skapar nya sårbarheter.",
        "Det kopplas vidare till hans kryptotes. Visser ser Ethereum, tokenisering och blockchain som ett potentiellt trust-lager för en värld där AI gör det svårare att veta vad och vem man kan lita på. Han menar att traditionella finansinstitut gradvis rör sig mot tokeniserade tillgångar, stablecoins och on-chain-marknader.",
        "Robinhood får återigen en central roll. Visser ser bolaget som en konvergenspunkt mellan traditionell finans, AI och crypto. Plattformen utvecklas från en aktiemäklare till något bredare: trading, crypto, retirement, banking, prediction markets, tokenisering och agentbaserad trading.",
        "Han jämför också dagens crypto- och AI-marknader med Amazon och internet under 1990- och 2000-talet. Hans poäng är att nya tekniska plattformar ofta är svåra att värdera med gamla mått. När en traditionell värderingsmodell slutligen fungerar kan en stor del av värdeökningen redan ha skett.",
        "Den övergripande tesen är därför att investerare måste välja vilken sida de vill stå på: den linjära världen där Fed, olja och räntor dominerar analysen — eller den exponentiella världen där AI, digital arbetskraft, compute, tokenisering och nya finansiella system förändrar hur ekonomin fungerar.",
        "<strong>Viktigaste slutsatserna enligt Visser</strong>",
        "1. Visser anser att AI och exponentiell produktivitet är viktigare än kortsiktiga rörelser i Fed, olja och obligationsräntor.",
        "2. Han menar att AGI/agentiska system nu har nått en nivå där AI kan utföra stora mängder mänskligt arbete parallellt.",
        "3. Compute, energi och möjligheten att distribuera intelligens kan bli större ekonomiska begränsningar än tillgången på mänsklig arbetskraft.",
        "4. AI kan både öka den totala ekonomiska potentialen och förkorta företags konkurrensfördelar, vilket påverkar terminalvärden och värderingsmultiplar.",
        "5. Visser använder AI för att bygga och backtesta tradingstrategier, vilket han ser som ett exempel på hur individer kan få större teknisk och entreprenöriell kraft.",
        "6. Framtidens trading kan bli mer agentbaserad, där många strategier testas och kombineras snarare än att en människa försöker hitta en perfekt modell.",
        "7. Stark efterfrågan på compute och höga GPU-hyrpriser kan innebära att AI-infrastrukturens ekonomi är bättre än skeptiker förväntar sig.",
        "8. Cybersecurity, privacy och trust blir samtidigt större problem när AI får mer makt och tillgång till data.",
        "9. Visser ser Ethereum och blockchain som möjliga trust-lager i en AI-driven ekonomi.",
        "10. Robinhood lyfts fram som en konvergens mellan traditionell finans, AI, crypto, tokenisering och agentisk trading.",
        "11. Crypto och AI kan enligt honom vara svåra att värdera med traditionella modeller, på samma sätt som internetbolag var under sin tidiga utveckling.",
        "12. Hans huvudbudskap är att investerare måste tänka exponentiellt snarare än linjärt för att förstå vart marknaden är på väg."
      ],
      "en": [
        "Jordi Visser expands on his framework of linear versus exponential thinking. His central argument is that investors continue to spend too much time focusing on traditional macro variables such as oil prices, bond yields and Federal Reserve policy while the much larger structural change is happening in AI, digital labor and exponential productivity.",
        "Visser argues that the economy has changed structurally since the global financial crisis. In earlier cycles, growth was more dependent on interest-rate-sensitive sectors such as housing and autos. Today, he sees AI capex, digital businesses and technology-driven productivity as increasingly important economic engines. Because of that, he believes markets often overreact to relatively small changes in rates, inflation and oil.",
        "A major theme of the video is his claim that AGI has effectively arrived through the latest generation of AI models and agents. He highlights Astra and the movement toward systems that combine chat, agents, coding, desktop interaction and other tools in one environment.",
        "Visser sees AI agents as the beginning of a new form of digital labor. Traditional economic growth is commonly described through labor, capital and productivity. AI changes that equation because thousands of digital agents can work simultaneously without many of the human constraints associated with time, emotion and attention. In this framework, compute, energy and the ability to deploy intelligence become increasingly important constraints.",
        "He uses AI work on the Navier–Stokes problem as an example of why this could have consequences far beyond office productivity. If AI accelerates breakthroughs in energy, manufacturing, transportation, medicine and physics, the potential size of the economy could expand while the competitive advantages of existing businesses become less durable.",
        "This leads into his view on terminal value and valuation multiples. Visser believes AI may shorten the lifespan of many corporate moats. A business that looks structurally strong today could be disrupted much faster than in previous technological cycles. At the same time, the winners could grow much faster. As a result, traditional valuation frameworks may become increasingly difficult to apply.",
        "A large part of the video focuses on the practical use of AI. Visser describes using AI agents to build and backtest trading models without needing to be a traditional programmer. He sees this as an example of AI giving individuals greater agency — the ability to build products, strategies and businesses themselves.",
        "His own trading framework starts with a universe of structural beneficiaries, such as companies exposed to the AI infrastructure buildout, and then uses measures such as trend, rate of change, ATR, resets and breakout signals to identify entries and exits. The broader point, however, is not the specific strategy but the ability of AI to generate, test and reject large numbers of ideas rapidly.",
        "Visser therefore believes trading will increasingly become agentic. He highlights platforms such as Robinhood, Moomoo and Interactive Brokers as examples of where data, automated strategies and agents can converge. The objective is not necessarily to discover one perfect model, but to run several uncorrelated strategies and continuously search for new sources of alpha.",
        "On AI infrastructure, he argues that demand for compute remains extremely strong. He highlights the resilience of Nvidia H100 rental economics as evidence that older AI hardware may retain economic value for longer than skeptics expected. If compute pricing and utilization remain high, hyperscalers may be able to generate more cash flow from existing installed capacity than current bearish assumptions imply.",
        "Visser also emphasizes the risks. Rapid AI development increases cybersecurity, privacy and trust problems. He references cyberattacks, AI-assisted hacking and attacks on critical infrastructure as examples of the vulnerabilities created by more powerful AI systems.",
        "This links directly to his crypto thesis. Visser sees Ethereum, tokenization and blockchain as potential trust layers in a world where AI makes it harder to know what information, systems or actors can be trusted. Traditional financial institutions are gradually moving toward tokenized assets, stablecoins and on-chain markets.",
        "Robinhood again plays a central role in his framework. Visser sees the company as a convergence point between traditional finance, AI and crypto. It is evolving from a brokerage app into a broader financial platform involving trading, crypto, retirement, banking, prediction markets, tokenization and agentic trading.",
        "He also compares today's AI and crypto markets with Amazon and the early internet era. His argument is that revolutionary technologies are often extremely difficult to value using existing financial models. By the time traditional valuation metrics become comfortable and obvious, a large portion of the investment opportunity may already have passed.",
        "The overarching thesis is that investors need to decide which side of the divide they want to operate on: the linear world dominated by Fed decisions, oil and bond yields, or the exponential world shaped by AI, digital labor, compute, tokenization and new financial infrastructure.",
        "<strong>Key takeaways from Visser’s argument</strong>",
        "1. Visser believes AI and exponential productivity matter more than short-term moves in the Fed, oil or bond yields.",
        "2. He argues that AI agents have reached a point where they can perform large amounts of parallel knowledge work.",
        "3. Compute, energy and the deployment of intelligence may become more important economic constraints than human labor.",
        "4. AI could both expand the size of the economy and shorten the durability of corporate competitive advantages.",
        "5. Visser uses AI to build and backtest trading systems, illustrating how AI can increase individual technical and entrepreneurial capability.",
        "6. Trading may become increasingly agentic, with many strategies tested, filtered and combined automatically.",
        "7. Strong compute demand and resilient GPU rental economics may make AI infrastructure more profitable than bearish assumptions suggest.",
        "8. Cybersecurity, privacy and trust are becoming more important as AI gains greater capabilities and access.",
        "9. Visser sees Ethereum and blockchain as potential trust infrastructure for an AI-driven economy.",
        "10. Robinhood is presented as a convergence of traditional finance, AI, crypto, tokenization and agentic trading.",
        "11. AI and crypto may require new valuation frameworks, just as early internet businesses did.",
        "12. The central message is that investors must learn to think exponentially rather than linearly."
      ]
    },
    "disclaimer": "AI-genererad sammanfattning av videon. Kan innehålla fel. Åsikter och prognoser tillhör Jordi Visser, inte NTM; påståenden är inte oberoende verifierade. Se originalvideon för fullständigt sammanhang. AI-generated summary; views and forecasts belong to Jordi Visser, not NTM. Claims have not been independently verified."
  },
  {
    "title": "Jordi Visser och Anthony Pompliano om AI, krypto och makro",
    "date": "2026-09-13",
    "slug": "jordi-visser-anthony-pompliano-ai-krypto-makro",
    "category": "Video",
    "tags": [
      "AI",
      "Crypto",
      "Bitcoin",
      "Makro",
      "Tokenisering",
      "Robinhood"
    ],
    "excerpt": "AI-sammanfattning av Jordi Vissers samtal med Anthony Pompliano om AI, krypto och makro. Läs hans resonemang och slutsatser på svenska eller engelska.",
    "media": {
      "type": "youtube",
      "videoId": "Uzc3tBB9pLg",
      "externalUrl": "https://www.youtube.com/watch?v=Uzc3tBB9pLg"
    },
    "content": "<p><strong>Källa:</strong> Jordi Visser i samtal med Anthony Pompliano. Se originalvideon via YouTube-länken nedan.</p>",
    "summary": {
      "sv": [
        "Jordi Visser argumenterar för att många investerare fortfarande lägger för stor vikt vid traditionella makrofaktorer som räntor och oljepris, samtidigt som de underskattar hur snabbt AI förändrar ekonomin, bolagens vinstpotential och marknadens struktur.",
        "Hans huvudpoäng är att dagens ekonomi är mindre räntekänslig än tidigare. Bostäder och bilköp spelar fortfarande roll, men en allt större del av börsens utveckling drivs enligt honom av digitala affärsmodeller, AI-investeringar, växande marginaler och stark vinsttillväxt. Därför menar han att mindre förändringar i Fed-räntan eller oljepriset inte bör väga lika tungt som de gjorde i tidigare cykler.",
        "Ett återkommande tema är skillnaden mellan statiskt och dynamiskt tänkande. Ett statiskt synsätt antar att en förändring automatiskt leder till samma konsekvens som historiskt. Ett dynamiskt synsätt tar hänsyn till att företag, regeringar, teknologi och marknader anpassar sig. Visser menar att AI-eran kräver det senare eftersom tekniken förbättras i mycket hög takt.",
        "Samtalet går också in på marknadsstrukturen. Hedgefonder och professionella traders kan tvingas reagera snabbt på kortsiktiga data eftersom de har drawdown-gränser och riskmandat. AI-agenter saknar samma emotionella begränsningar, medan långsiktiga privatinvesterare kan välja att ignorera kortsiktigt brus. Visser ser därför kraftiga reaktioner på exempelvis PPI eller ränterörelser som potentiella möjligheter för investerare med längre tidshorisont.",
        "På kryptosidan är Visser fortsatt mycket optimistisk. Han jämför värderingen av krypto med internets tidiga år, då etablerade värderingsmått ännu inte fanns. Han menar att tokenisering, Ethereum-ekosystemet och Robinhood Chain kan vara början på en större förändring där traditionella tillgångar, kryptotillgångar och nya finansiella produkter flyttar on-chain.",
        "Robinhood lyfts fram som ett exempel på hur traditionell finans, crypto och AI börjar konvergera. Från att ha varit en enkel aktiemäklare har bolaget enligt Visser utvecklats mot en bredare plattform med prediction markets, crypto, tokenisering och agentbaserad trading. Han ser detta som en modell för hur framtidens finansmarknad kan utvecklas.",
        "Reglering är också central. Visser tror att tydligare amerikanska kryptoregler, exempelvis genom Clarity Act, skulle kunna öppna dörren för större institutionellt kapital och pensionsfonder. Hans tes är att Bitcoin kan fortsätta utvecklas även utan detta, men att tydligare regler skulle kunna höja värdet på hela crypto-ekosystemet.",
        "På AI-sidan beskriver han utvecklingen som extremt snabb. Nya modeller och agentfunktioner gör enligt honom ett tydligt steg från enkla chatbotar till system som faktiskt kan utföra arbete, bygga modeller, analysera data och hjälpa till med trading. Han menar att den här utvecklingen kan få stor påverkan på produktivitet, forskning, fysik, läkemedelsutveckling och företags långsiktiga värderingar.",
        "Samtidigt ökar betydelsen av cybersecurity, privacy och trust. När AI-agenter får mer tillgång till information och system blir datasäkerhet och kontroll över egen intelligens viktigare. Visser ser därför trust som en potentiellt allt viktigare ekonomisk tillgång i en AI-driven värld.",
        "Samtalet avslutas med Fed, Kevin Warsh, Scott Bessent och Trumpadministrationen. Visser och Anthony diskuterar hur politik och centralbank kan påverka marknaden på kort sikt, men den större tesen är att amerikansk politik i praktiken är mycket stödjande för AI, crypto och teknologisk utveckling. Visser menar därför att det är svårt att vara långsiktigt bearish samtidigt som både den privata sektorn och politiken fokuserar på att vinna AI-kapplöpningen.",
        "Den övergripande bilden är mycket bullish: Visser anser att marknaden fortfarande fokuserar för mycket på gamla makrovariabler och för lite på den exponentiella tekniska förändringen som sker inom AI, crypto och digital finans.",
        "<strong>Viktigaste slutsatserna enligt Visser</strong>",
        "1. Visser tycker att AI-driven vinsttillväxt och produktivitet är viktigare än små förändringar i räntor och oljepris.",
        "2. Han skiljer mellan statiskt och dynamiskt tänkande och menar att gamla ekonomiska samband inte alltid fungerar i en snabbt föränderlig ekonomi.",
        "3. Kortsiktiga makroreaktioner kan skapa möjligheter för långsiktiga investerare när professionella aktörer tvingas reagera snabbt.",
        "4. AI-agenter kan förändra marknadsstrukturen eftersom de inte påverkas av emotioner och riskmandat på samma sätt som människor.",
        "5. Visser är fortsatt bullish på Bitcoin och crypto och tror att en större bullmarknad kan vara i ett tidigt skede.",
        "6. Tokenisering ses som bron mellan traditionell finans och crypto.",
        "7. Robinhood lyfts fram som ett exempel på konvergens mellan aktier, crypto, prediction markets och AI-baserad trading.",
        "8. Tydligare kryptoregler kan göra det lättare för pensionsfonder och institutioner att investera i ekosystemet.",
        "9. AI-utvecklingen går enligt Visser så snabbt att marknaden kan underskatta effekterna på framtida vinster och terminalvärden.",
        "10. Cybersecurity, privacy och trust kan bli ännu viktigare när AI får större tillgång till data och kritiska system."
      ],
      "en": [
        "Jordi Visser argues that many investors remain too focused on traditional macro variables such as interest rates and oil prices while underestimating how quickly AI is changing the economy, corporate earnings potential and market structure.",
        "His core argument is that the modern economy is less interest-rate sensitive than in previous cycles. Housing and auto demand still matter, but a growing share of equity-market performance is driven by digital businesses, AI investment, rising margins and strong earnings growth. Because of that, he believes small changes in Fed policy or oil prices deserve less weight than investors often give them.",
        "A recurring theme is the distinction between static and dynamic thinking. Static thinking assumes that a change will automatically produce the same outcome it did historically. Dynamic thinking considers how businesses, governments, technology and markets adapt. Visser argues that the AI era requires a much more dynamic framework because technological progress is accelerating so quickly.",
        "The discussion also focuses on market structure. Hedge funds and professional traders often have to react immediately to economic releases because of drawdown limits and risk constraints. AI agents do not have the same emotional limitations, while long-term retail investors can choose to look through short-term volatility. Visser therefore sees sharp reactions to data such as PPI or rate moves as potential opportunities for investors with longer time horizons.",
        "On crypto, Visser remains highly bullish. He compares crypto valuation today with the early internet, when investors had not yet developed reliable valuation metrics. He believes tokenization, Ethereum and Robinhood Chain may represent the beginning of a broader shift in which traditional assets, crypto assets and new financial products increasingly move on-chain.",
        "Robinhood is highlighted as an example of convergence between traditional finance, crypto and AI. What began as a low-cost stock brokerage has evolved into a broader platform involving crypto, prediction markets, tokenization and agentic trading. Visser sees this as a possible template for the future financial system.",
        "Regulation is another major theme. Visser believes clearer US crypto regulation, including potential progress around the Clarity Act, could unlock greater institutional and pension-fund participation. His view is that Bitcoin can continue rising without it, but clearer rules could materially increase the value of the broader crypto ecosystem.",
        "On AI, Visser describes the pace of progress as extraordinary. New models and agent capabilities are moving beyond simple chatbots toward systems that can perform work, build models, analyze data and assist with trading. He argues that this could have major long-term consequences for productivity, scientific research, physics, drug discovery and corporate valuations.",
        "At the same time, cybersecurity, privacy and trust become increasingly important. As AI systems gain more access to data and infrastructure, protecting information and controlling proprietary intelligence becomes more valuable. Visser sees trust itself becoming a more important economic asset in an AI-driven world.",
        "The conversation also covers the Fed, Kevin Warsh, Scott Bessent and the Trump administration. While policy and central-bank decisions can influence markets in the short term, the broader thesis is that US policy is strongly supportive of AI, crypto and technological leadership. Visser therefore finds it difficult to remain structurally bearish while both the private sector and policymakers are focused on winning the AI race.",
        "The overall message is strongly bullish: Visser believes markets are still paying too much attention to old macro variables and not enough attention to the exponential technological change taking place across AI, crypto and digital finance.",
        "<strong>Key takeaways from Visser’s argument</strong>",
        "1. Visser believes AI-driven earnings growth and productivity matter more than small moves in rates or oil.",
        "2. He emphasizes dynamic thinking over relying blindly on historical economic relationships.",
        "3. Short-term macro-driven volatility may create opportunities for long-term investors.",
        "4. AI agents may change market structure because they do not operate with the same emotional constraints as human traders.",
        "5. Visser remains bullish on Bitcoin and crypto and believes a larger bull market may still be in its early stages.",
        "6. Tokenization is viewed as a bridge between traditional finance and crypto.",
        "7. Robinhood is presented as an example of the convergence of stocks, crypto, prediction markets and agentic trading.",
        "8. Clearer crypto regulation could unlock more participation from pension funds and large institutions.",
        "9. Visser believes markets may be underpricing the long-term economic impact of rapid AI progress.",
        "10. Cybersecurity, privacy and trust are likely to become increasingly important as AI gains access to more data and infrastructure."
      ]
    },
    "disclaimer": "AI-genererad sammanfattning av samtalet. Kan innehålla fel. Åsikter och prognoser tillhör deltagarna, inte NTM; påståenden är inte oberoende verifierade. Se originalvideon för fullständigt sammanhang. AI-generated summary; views and forecasts belong to the speakers, not NTM. Claims have not been independently verified."
  },
  {
    title: 'Palantir väljer Nebius som föredragen partner för Sovereign AI',
    date: '2026-09-08',
    slug: 'palantir-nebius-sovereign-ai',
    category: 'Nyheter',
    tags: ['Nebius', 'Palantir', 'Sovereign AI'],
    previewPosition: 'top',
    excerpt: 'Palantir väljer Nebius som sin föredragna partner för Sovereign AI-infrastruktur – ett nytt partnerskap som integrerar Nebius AI-infrastruktur med Palantirs plattform.',
    media: {
      type: 'carousel',
      images: [
        { src: 'images/posts/nebius-2026-09-08/01.png', alt: 'Palantir och Nebius i partnerskapet för Sovereign AI' },
        { src: 'images/posts/nebius-2026-09-08/02.png', alt: 'Nebius AI-infrastruktur och Palantirs plattform' },
        { src: 'images/posts/nebius-2026-09-08/03.png', alt: 'Sovereign AI-infrastruktur från Nebius och Palantir' }
      ]
    },
    content: '<p>Palantir väljer Nebius som sin föredragna partner för Sovereign AI-infrastruktur.</p><p>Det nya partnerskapet innebär att Nebius AI-cloud, compute och inference ska integreras med Palantirs plattform och erbjudas till berättigade kommersiella kunder.</p><p>Tanken är att företag ska kunna köra och utveckla egna AI-modeller på Nebius infrastruktur – samtidigt som de behåller kontrollen över sin data, sina modeller och sin compute.</p><p>Bolagen ska även samarbeta för att få ny AI-kapacitet online snabbare, bland annat genom modulära datacenter på platser där kraft redan finns tillgänglig.</p><p>För Nebius tycker jag framför allt att detta är ytterligare ett kvitto på deras plattform. Palantir hade kunnat välja många infrastrukturpartners – men väljer Nebius som sin föredragna partner inom Sovereign AI.</p><p>Efter ett starkt Q2 fortsätter Nebius alltså att bygga både kapacitet, kundrelationer och partnerskap.</p><p><strong>Disclosure:</strong> Jag äger aktier i Nebius.</p>'
  },
  {
    title: 'Bank of America ser 65% uppsida i ASML – High-NA EUV tar nästa steg',
    date: '2026-09-08',
    slug: 'asml-bank-of-america-high-na-euv',
    category: 'Nyheter',
    tags: ['ASML', 'High-NA EUV'],
    previewPosition: 'top',
    excerpt: 'Bank of America upprepar köp på ASML med riktkurs €2 452 samtidigt som nästa generations High-NA EUV närmar sig bredare användning.',
    media: {
      type: 'carousel',
      images: [
        { src: 'images/posts/asml-2026-09-08/01.png', alt: 'ASML och Bank of Americas riktkurs' },
        { src: 'images/posts/asml-2026-09-08/02.png', alt: 'High-NA EUV och nästa steg i tekniken' }
      ]
    },
    content: '<p>Bank of America upprepar KÖP på ASML med en riktkurs på €2 452 – cirka 65% över dagens nivå.</p><p>Samtidigt fortsätter nyheterna kring nästa generations High-NA EUV.</p><p>Samsung planerar att använda tekniken i DRAM-produktion från 2028, medan TSMC siktar på avancerad högvolymproduktion från 2030.</p><p>ASML arbetar dessutom tillsammans med industrin på större 12-tums fotomasker. Lyckas övergången väntas produktiviteten i High-NA-systemen kunna öka med omkring 40%.</p><p>Det stärker det långsiktiga caset: mer avancerade AI-chip kräver allt mer avancerad tillverkning – där ASML sitter i en unik position.</p><p>Efter Q2 höjde ASML även prognosen för 2026 till €43–45 miljarder i omsättning och 54–56% bruttomarginal.</p><p><strong>Disclosure:</strong> Jag äger aktier i ASML.</p>'
  },
  {
    title: 'Så hänger min AI-portfölj ihop',
    date: '2026-09-05',
    slug: 'ai-portfolj',
    category: 'Portfölj',
    tags: ['AI', 'Semiconductors', 'Infrastruktur', 'Cybersecurity'],
    previewPosition: 'top',
    excerpt: 'AI är mycket mer än bara Nvidia och datacenter. Här är hur bolagen i min AI-portfölj hänger ihop genom hela kedjan – från råmaterial och halvledare till infrastruktur, cybersäkerhet och slutprodukter.',
    media: {
      type: 'carousel',
      images: [
        { src: 'images/posts/ai-portfolj/01.png', alt: 'Översikt över AI-portföljen' },
        { src: 'images/posts/ai-portfolj/02.png', alt: 'AI-portföljens halvledarkedja' },
        { src: 'images/posts/ai-portfolj/03.png', alt: 'AI-portföljens infrastruktur och cybersäkerhet' },
        { src: 'images/posts/ai-portfolj/04.png', alt: 'AI-portföljens slutprodukter' }
      ]
    },
    instagramUrl: 'https://www.instagram.com/ingencopycat/',
    content: '<p>AI är en kedja där många olika typer av bolag bidrar. Bilderna visar hur min portfölj är uppbyggd från råmaterial och halvledare till infrastruktur, cybersäkerhet och slutprodukter.</p>'
  },
  {
    title: 'Think It’s Too Late to Buy Micron Stock? Watch This',
    date: '2026-09-03',
    slug: 'micron-ai-memory',
    category: 'Video',
    tags: ['Micron', 'AI', 'Memory', 'Semiconductors'],
    excerpt: 'En AI-sammanfattning av videons tes om Micron, minnesmarknaden och den växande efterfrågan från AI.',
    media: {
      type: 'youtube',
      videoId: 'a7GT2OtnwtU',
      externalUrl: 'https://www.youtube.com/watch?v=a7GT2OtnwtU'
    },
    content: '',
    summary: {
      sv: [
        'Micron-caset har enligt videon blivit betydligt starkare. Huvudargumentet är att AI-boomen driver efterfrågan på DRAM, NAND och HBM mycket snabbare än industrin kan öka produktionen. Nvidia uppges exempelvis ha ökat sina inköpsåtaganden från 119 miljarder dollar till 279 miljarder dollar på ett kvartal, huvudsakligen kopplat till minne, med åtaganden som sträcker sig ända till 2029.',
        'En central del av tesen är skillnaden mellan utbud och efterfrågan. I videon citeras Elon Musk med uppskattningen att minnesproduktionen växer omkring 20 % per år, medan efterfrågan kan växa omkring 200 % per år eller mer. Om den bilden stämmer menar skaparen att de nya fabriker som börjar komma online 2027–2028 inte nödvändigtvis räcker för att snabbt eliminera flaskhalsen.',
        'Samtidigt pekar videon på fortsatt stigande minnespriser. Augustidata som tas upp visar kraftigare prisökningar för DRAM och NAND, och Bank of Americas AI-tracker uppges ha visat DRAM-priser upp 8 % månad över månad samtidigt som AI-tokenpriser och B200 GPU-hyror föll. Detta används som stöd för att minne håller på att bli en allt viktigare flaskhals i AI-stacken.',
        'Microns produktmix lyfts också fram. Bolagets HBM4-ramp uppges gå dubbelt så snabbt som HBM3E-rampen, samtidigt som Micron får fler långsiktiga kunder. Tesla nämns specifikt: Elon Musk säger enligt videon att Tesla fått en betydande framtida minnesallokering från Micron och tecknar fleråriga avtal.',
        'Videon argumenterar dessutom för att Wall Street hela tiden tvingas revidera upp framtida vinstförväntningar. Trots det beskriver skaparen Microns forward P/E som omkring 6,5x och price/free cash flow som strax över 9x, vilket han anser är lågt om den högre intjäningsnivån blir mer uthållig än marknaden räknar med.',
        'Kassaflödet är ytterligare en del av caset. Videon uppger att Microns kassa vuxit från 14,5 miljarder dollar till 26 miljarder dollar, samtidigt som skulden minskat från cirka 16 miljarder dollar till 6 miljarder dollar. Skaparen hänvisar också till UBS uppskattning att Micron potentiellt skulle kunna återköpa mer än 40 % av aktierna till slutet av 2028, medan Microns CFO säger att bolaget över tid vill återföra överskottskassa till aktieägarna, främst genom återköp.',
        '<strong>Slutsats:</strong> Skaparen fortsätter köpa Micron under 1 000 dollar och ser 2 000 dollar som ett mer konservativt mål, medan hans egentliga bull case är omkring 3 000 dollar. Tesens kärna är inte bara högre värderingsmultiplar utan att AI-driven minnesefterfrågan kan göra Microns extraordinära intjäningskraft betydligt mer uthållig än marknaden förväntar sig.'
      ],
      en: [
        'The video argues that Micron’s earnings power may be undergoing a structural change rather than another short-lived memory cycle. AI demand for DRAM, NAND and HBM is presented as growing faster than industry supply.',
        'Memory pricing, Micron’s HBM4 ramp and long-term customer commitments are used as evidence that memory is becoming a more important bottleneck in the AI stack.',
        'The creator also argues that Micron remains inexpensive if the higher earnings level proves sustainable, citing a forward P/E of roughly 6.5x and price-to-free-cash-flow of just over 9x.',
        '<strong>Conclusion:</strong> The creator continues buying Micron below $1,000 and describes $2,000 as a more conservative target. The thesis depends on AI-driven memory demand remaining stronger and longer-lasting than the market expects.'
      ]
    },
    disclaimer: 'AI-sammanfattning baserad på videons transkribering. Kan innehålla fel. Påståenden och siffror från videon är inte oberoende verifierade.'
  },
  {
    title: 'The Bond Market “Crash” Is a Trap — AI Agents Are About to Ignite Crypto',
    date: '2026-09-07',
    slug: 'jordi-visser-ai-agents-crypto',
    category: 'Video',
    tags: ['AI', 'Crypto', 'Bitcoin', 'Makro', 'Tokenisering'],
    excerpt: 'En AI-sammanfattning av Jordi Vissers tes om obligationsmarknaden, AI-agenter, tokenisering och varför krypto kan bli en central del av den agentiska ekonomin.',
    media: {
      type: 'youtube',
      videoId: 'er5mqvbDQU8',
      externalUrl: 'https://www.youtube.com/watch?v=er5mqvbDQU8'
    },
    content: '',
    summary: {
      sv: [
        '<strong>Jordi Vissers huvudtes</strong>',
        'Jordi Visser menar att investerare fokuserar för mycket på stigande obligationsräntor och för lite på en betydligt större strukturell förändring: konvergensen mellan AI-agenter och krypto.',
        'Hans resonemang binder samman tre områden – makro, AI och digitala tillgångar. Obligationsmarknaden visar enligt honom ännu inga tydliga tecken på systemstress, AI-investeringarna fortsätter samtidigt som agenttekniken accelererar, och tokenisering kan skapa den finansiella infrastrukturen som autonoma AI-system behöver.',
        '<strong>1. Obligationsoron är enligt Visser överdriven</strong>',
        'Visser argumenterar mot narrativet att stigande långräntor automatiskt innebär en kommande marknadskris.',
        'Han pekar bland annat på att kreditspreadar fortfarande är relativt lugna, inflationsförväntningarna inte signalerar någon dramatisk förändring och aktiemarknader samt banker fortsatt visar styrka.',
        'Hans poäng är inte att räntorna inte kan stiga. Han anser snarare att marknaden ännu inte visar de stressignaler som normalt skulle förknippas med en verklig obligationskris.',
        'Han räknar dessutom med att regeringar och myndigheter kommer försöka motverka en okontrollerad uppgång i långräntorna.',
        '<strong>2. Fundamentan för aktier är fortfarande stark</strong>',
        'Visser lyfter fortsatt starka vinstrevideringar, stigande globala vinstmarginaler och positiv konsumtion som argument för att den fundamentala bilden fortfarande stödjer aktier.',
        'Han använder bland annat PEG-resonemanget för S&P 500 och menar att värderingen måste sättas i relation till den förväntade vinsttillväxten.',
        'Hans slutsats är att det är svårt att beskriva hela marknaden som en bubbla så länge vinster och marginaler fortsätter växa i den takt han ser.',
        '<strong>3. AI-traden konsoliderar – den är inte död</strong>',
        'Visser beskriver den senaste svagheten i AI-relaterade aktier som en konsolidering efter en kraftig uppgång snarare än slutet på AI-cykeln.',
        'Han pekar särskilt på Nvidia som en viktig signal för hela AI- och halvledarkedjan.',
        'Nvidias relativa styrka, tillsammans med fortsatt efterfrågan på AI-servrar och compute, gör att han fortfarande är positiv till AI-infrastruktur på längre sikt.',
        'Han nämner även bolag som Micron, Marvell och Dell som delar av den bredare infrastrukturen.',
        'Samtidigt säger han att AI-traden för tillfället är "stuck in the mud" och att han själv har större vikt mot krypto.',
        '<strong>4. Räntor är inte den största risken för AI-ekonomin</strong>',
        'En viktig del av Vissers resonemang är att investerare överdriver hur känslig AI-ekonomin är för räntor.',
        'Han menar att ekonomin kring inference påverkas betydligt mer av modellpriser än av relativt små förändringar i finansieringskostnader.',
        'I hans exempel får en kraftig prisnedgång på AI-modeller större påverkan på marginalerna än en betydande uppgång i långräntorna.',
        'Därför ser han modellprispress hos ledande AI-labb som en viktigare risk att bevaka än mindre rörelser i obligationsräntorna.',
        '<strong>5. Från chatbot till AI-agent</strong>',
        'Här ligger videons viktigaste långsiktiga tema.',
        'AI utvecklas enligt Visser genom ungefär följande steg: chatbots → AI-assistenter → coding agents → personliga och arbetsflödesbaserade agenter → organisationer och svärmar av agenter.',
        'När AI inte längre bara svarar på frågor utan självständigt kan utföra uppgifter förändras infrastrukturen som behövs runt tekniken.',
        'Visser menar därför att företag och individer behöver lära sig agentbaserade arbetsflöden snarare än att enbart använda vanliga chatbotverktyg.',
        '<strong>6. AI-agenter behöver finansiell infrastruktur</strong>',
        'Det är här Visser kopplar ihop AI med krypto.',
        'Autonoma agenter som kan köpa tjänster, utföra arbete, investera eller interagera ekonomiskt behöver någon form av digital betalnings- och ägandeinfrastruktur.',
        'Visser ser därför stablecoins, tokeniserade tillgångar, digitala wallets, 24/7-marknader och programmerbara betalningar som potentiellt naturliga komponenter i en framtida agentekonomi.',
        'Hans centrala tes är att kryptons stora användargrupp i framtiden kanske inte främst blir människor – utan maskiner och AI-agenter.',
        '<strong>7. Tokenisering går från teori till faktisk användning</strong>',
        'Visser pekar på den växande marknaden för tokeniserade real-world assets och utvecklingen av tokeniserade aktier och andra finansiella produkter.',
        'Han lyfter bland annat Robinhood och utvecklingen mot handel och ägande av traditionella tillgångar via blockchainbaserad infrastruktur.',
        'I hans scenario går finansmarknaden gradvis från traditionella system till en hybridmodell där fler tillgångar kan handlas och ägas digitalt dygnet runt.',
        'Han ser detta som en strukturell trend snarare än en kortsiktig kryptocykel.',
        '<strong>8. Varför Bitcoin passar in i tesen</strong>',
        'Visser beskriver Bitcoin som en central del av den bredare kryptoekonomin och ser tillgången som ett sätt att få exponering mot utvecklingen.',
        'Hans argument är inte att Bitcoin själv kommer hantera alla agentbetalningar.',
        'Istället ser han Bitcoin som en slags övergripande exponering mot ett växande digitalt finansiellt ekosystem, ungefär som ett brett index kan representera en större ekonomi.',
        'Han kopplar därför samman Bitcoin med AI, tokenisering och den fortsatta digitaliseringen av finans.',
        '<strong>9. Risk/reward snarare än säkerhet</strong>',
        'Mot slutet av videon beskriver Visser sitt investeringssätt som sannolikhetsbaserat.',
        'Han försöker inte hitta något som garanterat kommer fungera. Han letar efter situationer där den potentiella uppsidan är stor i förhållande till sannolikheten marknaden verkar prisa in.',
        'Hans AI/krypto-tes bygger därför på frågan: hur stor är sannolikheten att AI-agenter, tokenisering och digitala finansiella system växer kraftigt under kommande år?',
        'Om marknaden underskattar den sannolikheten ser han en asymmetrisk möjlighet.',
        'Det är en investeringstes – inte ett säkert utfall.',
        '<strong>NTM – Kort sammanfattat</strong>',
        'Jordi Vissers resonemang kan sammanfattas som en kedja: AI blir smartare → AI-agenter kan utföra allt fler uppgifter självständigt → agenter börjar interagera ekonomiskt → behovet av digitala betalningar och digitalt ägande växer → stablecoins, tokenisering och krypto kan bli en del av infrastrukturen → det kan skapa en betydligt större kryptoekonomi än den som enbart drivs av mänsklig spekulation idag.',
        'Samtidigt anser Visser att obligationsoron är överdriven, att fundamentan för aktier fortfarande är stark och att AI-traden konsoliderar snarare än kollapsar.',
        'Den stora frågan är därför inte bara hur snabbt AI fortsätter utvecklas. Det är vad som händer när AI själv börjar bli en ekonomisk aktör.'
      ],
      en: [
        '<strong>Jordi Visser\'s core thesis</strong>',
        'Jordi Visser argues that investors are focusing too much on rising bond yields and too little on a much larger structural shift: the convergence of AI agents and crypto.',
        'His reasoning ties together three areas – macro, AI and digital assets. According to him, the bond market still shows no clear signs of systemic stress, AI investment continues while agent technology accelerates, and tokenization can create the financial infrastructure that autonomous AI systems need.',
        '<strong>1. Bond market anxiety is, in Visser\'s view, overstated</strong>',
        'Visser argues against the narrative that rising long-term yields automatically imply an approaching market crisis.',
        'He points, among other things, to credit spreads still being relatively calm, inflation expectations not signaling any dramatic change, and equity markets and banks continuing to show strength.',
        'His point is not that yields cannot rise. Rather, he believes the market is not yet showing the stress signals that would normally be associated with a real bond market crisis.',
        'He also expects governments and authorities to try to counteract an uncontrolled rise in long-term yields.',
        '<strong>2. The fundamentals for stocks are still strong</strong>',
        'Visser highlights continued strong earnings revisions, rising global profit margins and positive consumption as arguments that the fundamental picture still supports stocks.',
        'He uses, among other things, the PEG reasoning for the S&P 500 and argues that valuation must be seen in relation to expected earnings growth.',
        'His conclusion is that it is difficult to describe the entire market as a bubble as long as earnings and margins keep growing at the pace he sees.',
        '<strong>3. The AI trade is consolidating – it is not dead</strong>',
        'Visser describes the recent weakness in AI-related stocks as a consolidation after a sharp rally rather than the end of the AI cycle.',
        'He points in particular to Nvidia as an important signal for the entire AI and semiconductor chain.',
        'Nvidia\'s relative strength, together with continued demand for AI servers and compute, means he remains positive on AI infrastructure over the longer term.',
        'He also mentions companies such as Micron, Marvell and Dell as part of the broader infrastructure.',
        'At the same time, he says the AI trade is currently "stuck in the mud" and that he himself is more heavily weighted toward crypto.',
        '<strong>4. Interest rates are not the biggest risk to the AI economy</strong>',
        'An important part of Visser\'s reasoning is that investors overstate how sensitive the AI economy is to interest rates.',
        'He argues that the economics of inference are affected far more by model pricing than by relatively small changes in financing costs.',
        'In his example, a sharp price decline for AI models has a bigger impact on margins than a significant rise in long-term yields.',
        'He therefore sees model price pressure among leading AI labs as a more important risk to watch than smaller moves in bond yields.',
        '<strong>5. From chatbot to AI agent</strong>',
        'This is the video\'s most important long-term theme.',
        'According to Visser, AI is evolving through roughly the following steps: chatbots → AI assistants → coding agents → personal and workflow-based agents → organizations and swarms of agents.',
        'When AI no longer just answers questions but can independently carry out tasks, the infrastructure needed around the technology changes.',
        'Visser therefore argues that companies and individuals need to learn agent-based workflows rather than only using ordinary chatbot tools.',
        '<strong>6. AI agents need financial infrastructure</strong>',
        'This is where Visser connects AI with crypto.',
        'Autonomous agents that can buy services, perform work, invest or interact economically need some form of digital payment and ownership infrastructure.',
        'Visser therefore sees stablecoins, tokenized assets, digital wallets, 24/7 markets and programmable payments as potentially natural components of a future agent economy.',
        'His central thesis is that crypto\'s largest user base in the future might not primarily be humans – but machines and AI agents.',
        '<strong>7. Tokenization is moving from theory to actual use</strong>',
        'Visser points to the growing market for tokenized real-world assets and the development of tokenized stocks and other financial products.',
        'He highlights, among other things, Robinhood and the shift toward trading and owning traditional assets via blockchain-based infrastructure.',
        'In his scenario, financial markets gradually move from traditional systems to a hybrid model where more assets can be traded and owned digitally around the clock.',
        'He sees this as a structural trend rather than a short-term crypto cycle.',
        '<strong>8. Why Bitcoin fits the thesis</strong>',
        'Visser describes Bitcoin as a central part of the broader crypto economy and sees the asset as a way to gain exposure to that development.',
        'His argument is not that Bitcoin itself will handle all agent payments.',
        'Instead, he sees Bitcoin as a kind of broad exposure to a growing digital financial ecosystem, somewhat like a broad index can represent a larger economy.',
        'He therefore links Bitcoin to AI, tokenization and the continued digitization of finance.',
        '<strong>9. Risk/reward rather than certainty</strong>',
        'Toward the end of the video, Visser describes his investing approach as probability-based.',
        'He is not trying to find something guaranteed to work. He looks for situations where the potential upside is large relative to the probability the market appears to be pricing in.',
        'His AI/crypto thesis therefore rests on the question: how likely is it that AI agents, tokenization and digital financial systems grow significantly over the coming years?',
        'If the market underestimates that probability, he sees an asymmetric opportunity.',
        'It is an investment thesis – not a guaranteed outcome.',
        '<strong>NTM – Quick summary</strong>',
        'Jordi Visser\'s reasoning can be summarized as a chain: AI gets smarter → AI agents can carry out more and more tasks independently → agents start interacting economically → the need for digital payments and digital ownership grows → stablecoins, tokenization and crypto can become part of the infrastructure → this can create a much larger crypto economy than the one driven purely by human speculation today.',
        'At the same time, Visser believes bond market anxiety is overstated, that the fundamentals for stocks remain strong, and that the AI trade is consolidating rather than collapsing.',
        'The big question, therefore, is not just how fast AI keeps developing. It is what happens when AI itself starts becoming an economic actor.'
      ]
    },
    disclaimer: 'AI-sammanfattning baserad på videons transkribering. Kan innehålla fel. Åsikterna tillhör Jordi Visser, inte NTM, och detta är inte finansiell rådgivning. Se originalvideon för fullständigt sammanhang.'
  }
];