const NTM_POSTS = [
  {
    title: 'Palantir väljer Nebius som föredragen partner för Sovereign AI',
    date: '2026-09-08',
    slug: 'palantir-nebius-sovereign-ai',
    category: 'Nyheter',
    tags: ['Nebius', 'Palantir', 'Sovereign AI'],
    previewPosition: 'top',
    excerpt: 'Palantir väljer Nebius som sin föredragna partner för Sovereign AI-infrastruktur – ett nytt partnerskap som integrerar Nebius AI-infrastruktur med Palantirs plattform.',
    media: {
      type: 'carousel',
      images: [
        { src: 'images/posts/nebius-2026-09-08/01.png', alt: 'Palantir och Nebius i partnerskapet för Sovereign AI' },
        { src: 'images/posts/nebius-2026-09-08/02.png', alt: 'Nebius AI-infrastruktur och Palantirs plattform' },
        { src: 'images/posts/nebius-2026-09-08/03.png', alt: 'Sovereign AI-infrastruktur från Nebius och Palantir' }
      ]
    },
    content: '<p>Palantir väljer Nebius som sin föredragna partner för Sovereign AI-infrastruktur.</p><p>Det nya partnerskapet innebär att Nebius AI-cloud, compute och inference ska integreras med Palantirs plattform och erbjudas till berättigade kommersiella kunder.</p><p>Tanken är att företag ska kunna köra och utveckla egna AI-modeller på Nebius infrastruktur – samtidigt som de behåller kontrollen över sin data, sina modeller och sin compute.</p><p>Bolagen ska även samarbeta för att få ny AI-kapacitet online snabbare, bland annat genom modulära datacenter på platser där kraft redan finns tillgänglig.</p><p>För Nebius tycker jag framför allt att detta är ytterligare ett kvitto på deras plattform. Palantir hade kunnat välja många infrastrukturpartners – men väljer Nebius som sin föredragna partner inom Sovereign AI.</p><p>Efter ett starkt Q2 fortsätter Nebius alltså att bygga både kapacitet, kundrelationer och partnerskap.</p><p><strong>Disclosure:</strong> Jag äger aktier i Nebius.</p>'
  },
  {
    title: 'Bank of America ser 65% uppsida i ASML – High-NA EUV tar nästa steg',
    date: '2026-09-08',
    slug: 'asml-bank-of-america-high-na-euv',
    category: 'Nyheter',
    tags: ['ASML', 'High-NA EUV'],
    previewPosition: 'top',
    excerpt: 'Bank of America upprepar köp på ASML med riktkurs €2 452 samtidigt som nästa generations High-NA EUV närmar sig bredare användning.',
    media: {
      type: 'carousel',
      images: [
        { src: 'images/posts/asml-2026-09-08/01.png', alt: 'ASML och Bank of Americas riktkurs' },
        { src: 'images/posts/asml-2026-09-08/02.png', alt: 'High-NA EUV och nästa steg i tekniken' }
      ]
    },
    content: '<p>Bank of America upprepar KÖP på ASML med en riktkurs på €2 452 – cirka 65% över dagens nivå.</p><p>Samtidigt fortsätter nyheterna kring nästa generations High-NA EUV.</p><p>Samsung planerar att använda tekniken i DRAM-produktion från 2028, medan TSMC siktar på avancerad högvolymproduktion från 2030.</p><p>ASML arbetar dessutom tillsammans med industrin på större 12-tums fotomasker. Lyckas övergången väntas produktiviteten i High-NA-systemen kunna öka med omkring 40%.</p><p>Det stärker det långsiktiga caset: mer avancerade AI-chip kräver allt mer avancerad tillverkning – där ASML sitter i en unik position.</p><p>Efter Q2 höjde ASML även prognosen för 2026 till €43–45 miljarder i omsättning och 54–56% bruttomarginal.</p><p><strong>Disclosure:</strong> Jag äger aktier i ASML.</p>'
  },
  {
    title: 'Så hänger min AI-portfölj ihop',
    date: '2026-09-05',
    slug: 'ai-portfolj',
    category: 'Portfölj',
    tags: ['AI', 'Semiconductors', 'Infrastruktur', 'Cybersecurity'],
    previewPosition: 'top',
    excerpt: 'AI är mycket mer än bara Nvidia och datacenter. Här är hur bolagen i min AI-portfölj hänger ihop genom hela kedjan – från råmaterial och halvledare till infrastruktur, cybersäkerhet och slutprodukter.',
    media: {
      type: 'carousel',
      images: [
        { src: 'images/posts/ai-portfolj/01.png', alt: 'Översikt över AI-portföljen' },
        { src: 'images/posts/ai-portfolj/02.png', alt: 'AI-portföljens halvledarkedja' },
        { src: 'images/posts/ai-portfolj/03.png', alt: 'AI-portföljens infrastruktur och cybersäkerhet' },
        { src: 'images/posts/ai-portfolj/04.png', alt: 'AI-portföljens slutprodukter' }
      ]
    },
    instagramUrl: 'https://www.instagram.com/ingencopycat/',
    content: '<p>AI är en kedja där många olika typer av bolag bidrar. Bilderna visar hur min portfölj är uppbyggd från råmaterial och halvledare till infrastruktur, cybersäkerhet och slutprodukter.</p>'
  },
  {
    title: 'Think It’s Too Late to Buy Micron Stock? Watch This',
    date: '2026-09-03',
    slug: 'micron-ai-memory',
    category: 'Video',
    tags: ['Micron', 'AI', 'Memory', 'Semiconductors'],
    excerpt: 'En AI-sammanfattning av videons tes om Micron, minnesmarknaden och den växande efterfrågan från AI.',
    media: {
      type: 'youtube',
      videoId: 'a7GT2OtnwtU',
      externalUrl: 'https://www.youtube.com/watch?v=a7GT2OtnwtU'
    },
    content: '',
    summary: {
      sv: [
        'Micron-caset har enligt videon blivit betydligt starkare. Huvudargumentet är att AI-boomen driver efterfrågan på DRAM, NAND och HBM mycket snabbare än industrin kan öka produktionen. Nvidia uppges exempelvis ha ökat sina inköpsåtaganden från 119 miljarder dollar till 279 miljarder dollar på ett kvartal, huvudsakligen kopplat till minne, med åtaganden som sträcker sig ända till 2029.',
        'En central del av tesen är skillnaden mellan utbud och efterfrågan. I videon citeras Elon Musk med uppskattningen att minnesproduktionen växer omkring 20 % per år, medan efterfrågan kan växa omkring 200 % per år eller mer. Om den bilden stämmer menar skaparen att de nya fabriker som börjar komma online 2027–2028 inte nödvändigtvis räcker för att snabbt eliminera flaskhalsen.',
        'Samtidigt pekar videon på fortsatt stigande minnespriser. Augustidata som tas upp visar kraftigare prisökningar för DRAM och NAND, och Bank of Americas AI-tracker uppges ha visat DRAM-priser upp 8 % månad över månad samtidigt som AI-tokenpriser och B200 GPU-hyror föll. Detta används som stöd för att minne håller på att bli en allt viktigare flaskhals i AI-stacken.',
        'Microns produktmix lyfts också fram. Bolagets HBM4-ramp uppges gå dubbelt så snabbt som HBM3E-rampen, samtidigt som Micron får fler långsiktiga kunder. Tesla nämns specifikt: Elon Musk säger enligt videon att Tesla fått en betydande framtida minnesallokering från Micron och tecknar fleråriga avtal.',
        'Videon argumenterar dessutom för att Wall Street hela tiden tvingas revidera upp framtida vinstförväntningar. Trots det beskriver skaparen Microns forward P/E som omkring 6,5x och price/free cash flow som strax över 9x, vilket han anser är lågt om den högre intjäningsnivån blir mer uthållig än marknaden räknar med.',
        'Kassaflödet är ytterligare en del av caset. Videon uppger att Microns kassa vuxit från 14,5 miljarder dollar till 26 miljarder dollar, samtidigt som skulden minskat från cirka 16 miljarder dollar till 6 miljarder dollar. Skaparen hänvisar också till UBS uppskattning att Micron potentiellt skulle kunna återköpa mer än 40 % av aktierna till slutet av 2028, medan Microns CFO säger att bolaget över tid vill återföra överskottskassa till aktieägarna, främst genom återköp.',
        '<strong>Slutsats:</strong> Skaparen fortsätter köpa Micron under 1 000 dollar och ser 2 000 dollar som ett mer konservativt mål, medan hans egentliga bull case är omkring 3 000 dollar. Tesens kärna är inte bara högre värderingsmultiplar utan att AI-driven minnesefterfrågan kan göra Microns extraordinära intjäningskraft betydligt mer uthållig än marknaden förväntar sig.'
      ],
      en: [
        'The video argues that Micron’s earnings power may be undergoing a structural change rather than another short-lived memory cycle. AI demand for DRAM, NAND and HBM is presented as growing faster than industry supply.',
        'Memory pricing, Micron’s HBM4 ramp and long-term customer commitments are used as evidence that memory is becoming a more important bottleneck in the AI stack.',
        'The creator also argues that Micron remains inexpensive if the higher earnings level proves sustainable, citing a forward P/E of roughly 6.5x and price-to-free-cash-flow of just over 9x.',
        '<strong>Conclusion:</strong> The creator continues buying Micron below $1,000 and describes $2,000 as a more conservative target. The thesis depends on AI-driven memory demand remaining stronger and longer-lasting than the market expects.'
      ]
    },
    disclaimer: 'AI-sammanfattning baserad på videons transkribering. Kan innehålla fel. Påståenden och siffror från videon är inte oberoende verifierade.'
  },
  {
    title: 'The Bond Market “Crash” Is a Trap — AI Agents Are About to Ignite Crypto',
    date: '2026-09-07',
    slug: 'jordi-visser-ai-agents-crypto',
    category: 'Video',
    tags: ['AI', 'Crypto', 'Bitcoin', 'Makro', 'Tokenisering'],
    excerpt: 'En AI-sammanfattning av Jordi Vissers tes om obligationsmarknaden, AI-agenter, tokenisering och varför krypto kan bli en central del av den agentiska ekonomin.',
    media: {
      type: 'youtube',
      videoId: 'er5mqvbDQU8',
      externalUrl: 'https://www.youtube.com/watch?v=er5mqvbDQU8'
    },
    content: '',
    summary: {
      sv: [
        '<strong>Jordi Vissers huvudtes</strong>',
        'Jordi Visser menar att investerare fokuserar för mycket på stigande obligationsräntor och för lite på en betydligt större strukturell förändring: konvergensen mellan AI-agenter och krypto.',
        'Hans resonemang binder samman tre områden – makro, AI och digitala tillgångar. Obligationsmarknaden visar enligt honom ännu inga tydliga tecken på systemstress, AI-investeringarna fortsätter samtidigt som agenttekniken accelererar, och tokenisering kan skapa den finansiella infrastrukturen som autonoma AI-system behöver.',
        '<strong>1. Obligationsoron är enligt Visser överdriven</strong>',
        'Visser argumenterar mot narrativet att stigande långräntor automatiskt innebär en kommande marknadskris.',
        'Han pekar bland annat på att kreditspreadar fortfarande är relativt lugna, inflationsförväntningarna inte signalerar någon dramatisk förändring och aktiemarknader samt banker fortsatt visar styrka.',
        'Hans poäng är inte att räntorna inte kan stiga. Han anser snarare att marknaden ännu inte visar de stressignaler som normalt skulle förknippas med en verklig obligationskris.',
        'Han räknar dessutom med att regeringar och myndigheter kommer försöka motverka en okontrollerad uppgång i långräntorna.',
        '<strong>2. Fundamentan för aktier är fortfarande stark</strong>',
        'Visser lyfter fortsatt starka vinstrevideringar, stigande globala vinstmarginaler och positiv konsumtion som argument för att den fundamentala bilden fortfarande stödjer aktier.',
        'Han använder bland annat PEG-resonemanget för S&P 500 och menar att värderingen måste sättas i relation till den förväntade vinsttillväxten.',
        'Hans slutsats är att det är svårt att beskriva hela marknaden som en bubbla så länge vinster och marginaler fortsätter växa i den takt han ser.',
        '<strong>3. AI-traden konsoliderar – den är inte död</strong>',
        'Visser beskriver den senaste svagheten i AI-relaterade aktier som en konsolidering efter en kraftig uppgång snarare än slutet på AI-cykeln.',
        'Han pekar särskilt på Nvidia som en viktig signal för hela AI- och halvledarkedjan.',
        'Nvidias relativa styrka, tillsammans med fortsatt efterfrågan på AI-servrar och compute, gör att han fortfarande är positiv till AI-infrastruktur på längre sikt.',
        'Han nämner även bolag som Micron, Marvell och Dell som delar av den bredare infrastrukturen.',
        'Samtidigt säger han att AI-traden för tillfället är "stuck in the mud" och att han själv har större vikt mot krypto.',
        '<strong>4. Räntor är inte den största risken för AI-ekonomin</strong>',
        'En viktig del av Vissers resonemang är att investerare överdriver hur känslig AI-ekonomin är för räntor.',
        'Han menar att ekonomin kring inference påverkas betydligt mer av modellpriser än av relativt små förändringar i finansieringskostnader.',
        'I hans exempel får en kraftig prisnedgång på AI-modeller större påverkan på marginalerna än en betydande uppgång i långräntorna.',
        'Därför ser han modellprispress hos ledande AI-labb som en viktigare risk att bevaka än mindre rörelser i obligationsräntorna.',
        '<strong>5. Från chatbot till AI-agent</strong>',
        'Här ligger videons viktigaste långsiktiga tema.',
        'AI utvecklas enligt Visser genom ungefär följande steg: chatbots → AI-assistenter → coding agents → personliga och arbetsflödesbaserade agenter → organisationer och svärmar av agenter.',
        'När AI inte längre bara svarar på frågor utan självständigt kan utföra uppgifter förändras infrastrukturen som behövs runt tekniken.',
        'Visser menar därför att företag och individer behöver lära sig agentbaserade arbetsflöden snarare än att enbart använda vanliga chatbotverktyg.',
        '<strong>6. AI-agenter behöver finansiell infrastruktur</strong>',
        'Det är här Visser kopplar ihop AI med krypto.',
        'Autonoma agenter som kan köpa tjänster, utföra arbete, investera eller interagera ekonomiskt behöver någon form av digital betalnings- och ägandeinfrastruktur.',
        'Visser ser därför stablecoins, tokeniserade tillgångar, digitala wallets, 24/7-marknader och programmerbara betalningar som potentiellt naturliga komponenter i en framtida agentekonomi.',
        'Hans centrala tes är att kryptons stora användargrupp i framtiden kanske inte främst blir människor – utan maskiner och AI-agenter.',
        '<strong>7. Tokenisering går från teori till faktisk användning</strong>',
        'Visser pekar på den växande marknaden för tokeniserade real-world assets och utvecklingen av tokeniserade aktier och andra finansiella produkter.',
        'Han lyfter bland annat Robinhood och utvecklingen mot handel och ägande av traditionella tillgångar via blockchainbaserad infrastruktur.',
        'I hans scenario går finansmarknaden gradvis från traditionella system till en hybridmodell där fler tillgångar kan handlas och ägas digitalt dygnet runt.',
        'Han ser detta som en strukturell trend snarare än en kortsiktig kryptocykel.',
        '<strong>8. Varför Bitcoin passar in i tesen</strong>',
        'Visser beskriver Bitcoin som en central del av den bredare kryptoekonomin och ser tillgången som ett sätt att få exponering mot utvecklingen.',
        'Hans argument är inte att Bitcoin själv kommer hantera alla agentbetalningar.',
        'Istället ser han Bitcoin som en slags övergripande exponering mot ett växande digitalt finansiellt ekosystem, ungefär som ett brett index kan representera en större ekonomi.',
        'Han kopplar därför samman Bitcoin med AI, tokenisering och den fortsatta digitaliseringen av finans.',
        '<strong>9. Risk/reward snarare än säkerhet</strong>',
        'Mot slutet av videon beskriver Visser sitt investeringssätt som sannolikhetsbaserat.',
        'Han försöker inte hitta något som garanterat kommer fungera. Han letar efter situationer där den potentiella uppsidan är stor i förhållande till sannolikheten marknaden verkar prisa in.',
        'Hans AI/krypto-tes bygger därför på frågan: hur stor är sannolikheten att AI-agenter, tokenisering och digitala finansiella system växer kraftigt under kommande år?',
        'Om marknaden underskattar den sannolikheten ser han en asymmetrisk möjlighet.',
        'Det är en investeringstes – inte ett säkert utfall.',
        '<strong>NTM – Kort sammanfattat</strong>',
        'Jordi Vissers resonemang kan sammanfattas som en kedja: AI blir smartare → AI-agenter kan utföra allt fler uppgifter självständigt → agenter börjar interagera ekonomiskt → behovet av digitala betalningar och digitalt ägande växer → stablecoins, tokenisering och krypto kan bli en del av infrastrukturen → det kan skapa en betydligt större kryptoekonomi än den som enbart drivs av mänsklig spekulation idag.',
        'Samtidigt anser Visser att obligationsoron är överdriven, att fundamentan för aktier fortfarande är stark och att AI-traden konsoliderar snarare än kollapsar.',
        'Den stora frågan är därför inte bara hur snabbt AI fortsätter utvecklas. Det är vad som händer när AI själv börjar bli en ekonomisk aktör.'
      ],
      en: [
        '<strong>Jordi Visser\'s core thesis</strong>',
        'Jordi Visser argues that investors are focusing too much on rising bond yields and too little on a much larger structural shift: the convergence of AI agents and crypto.',
        'His reasoning ties together three areas – macro, AI and digital assets. According to him, the bond market still shows no clear signs of systemic stress, AI investment continues while agent technology accelerates, and tokenization can create the financial infrastructure that autonomous AI systems need.',
        '<strong>1. Bond market anxiety is, in Visser\'s view, overstated</strong>',
        'Visser argues against the narrative that rising long-term yields automatically imply an approaching market crisis.',
        'He points, among other things, to credit spreads still being relatively calm, inflation expectations not signaling any dramatic change, and equity markets and banks continuing to show strength.',
        'His point is not that yields cannot rise. Rather, he believes the market is not yet showing the stress signals that would normally be associated with a real bond market crisis.',
        'He also expects governments and authorities to try to counteract an uncontrolled rise in long-term yields.',
        '<strong>2. The fundamentals for stocks are still strong</strong>',
        'Visser highlights continued strong earnings revisions, rising global profit margins and positive consumption as arguments that the fundamental picture still supports stocks.',
        'He uses, among other things, the PEG reasoning for the S&P 500 and argues that valuation must be seen in relation to expected earnings growth.',
        'His conclusion is that it is difficult to describe the entire market as a bubble as long as earnings and margins keep growing at the pace he sees.',
        '<strong>3. The AI trade is consolidating – it is not dead</strong>',
        'Visser describes the recent weakness in AI-related stocks as a consolidation after a sharp rally rather than the end of the AI cycle.',
        'He points in particular to Nvidia as an important signal for the entire AI and semiconductor chain.',
        'Nvidia\'s relative strength, together with continued demand for AI servers and compute, means he remains positive on AI infrastructure over the longer term.',
        'He also mentions companies such as Micron, Marvell and Dell as part of the broader infrastructure.',
        'At the same time, he says the AI trade is currently "stuck in the mud" and that he himself is more heavily weighted toward crypto.',
        '<strong>4. Interest rates are not the biggest risk to the AI economy</strong>',
        'An important part of Visser\'s reasoning is that investors overstate how sensitive the AI economy is to interest rates.',
        'He argues that the economics of inference are affected far more by model pricing than by relatively small changes in financing costs.',
        'In his example, a sharp price decline for AI models has a bigger impact on margins than a significant rise in long-term yields.',
        'He therefore sees model price pressure among leading AI labs as a more important risk to watch than smaller moves in bond yields.',
        '<strong>5. From chatbot to AI agent</strong>',
        'This is the video\'s most important long-term theme.',
        'According to Visser, AI is evolving through roughly the following steps: chatbots → AI assistants → coding agents → personal and workflow-based agents → organizations and swarms of agents.',
        'When AI no longer just answers questions but can independently carry out tasks, the infrastructure needed around the technology changes.',
        'Visser therefore argues that companies and individuals need to learn agent-based workflows rather than only using ordinary chatbot tools.',
        '<strong>6. AI agents need financial infrastructure</strong>',
        'This is where Visser connects AI with crypto.',
        'Autonomous agents that can buy services, perform work, invest or interact economically need some form of digital payment and ownership infrastructure.',
        'Visser therefore sees stablecoins, tokenized assets, digital wallets, 24/7 markets and programmable payments as potentially natural components of a future agent economy.',
        'His central thesis is that crypto\'s largest user base in the future might not primarily be humans – but machines and AI agents.',
        '<strong>7. Tokenization is moving from theory to actual use</strong>',
        'Visser points to the growing market for tokenized real-world assets and the development of tokenized stocks and other financial products.',
        'He highlights, among other things, Robinhood and the shift toward trading and owning traditional assets via blockchain-based infrastructure.',
        'In his scenario, financial markets gradually move from traditional systems to a hybrid model where more assets can be traded and owned digitally around the clock.',
        'He sees this as a structural trend rather than a short-term crypto cycle.',
        '<strong>8. Why Bitcoin fits the thesis</strong>',
        'Visser describes Bitcoin as a central part of the broader crypto economy and sees the asset as a way to gain exposure to that development.',
        'His argument is not that Bitcoin itself will handle all agent payments.',
        'Instead, he sees Bitcoin as a kind of broad exposure to a growing digital financial ecosystem, somewhat like a broad index can represent a larger economy.',
        'He therefore links Bitcoin to AI, tokenization and the continued digitization of finance.',
        '<strong>9. Risk/reward rather than certainty</strong>',
        'Toward the end of the video, Visser describes his investing approach as probability-based.',
        'He is not trying to find something guaranteed to work. He looks for situations where the potential upside is large relative to the probability the market appears to be pricing in.',
        'His AI/crypto thesis therefore rests on the question: how likely is it that AI agents, tokenization and digital financial systems grow significantly over the coming years?',
        'If the market underestimates that probability, he sees an asymmetric opportunity.',
        'It is an investment thesis – not a guaranteed outcome.',
        '<strong>NTM – Quick summary</strong>',
        'Jordi Visser\'s reasoning can be summarized as a chain: AI gets smarter → AI agents can carry out more and more tasks independently → agents start interacting economically → the need for digital payments and digital ownership grows → stablecoins, tokenization and crypto can become part of the infrastructure → this can create a much larger crypto economy than the one driven purely by human speculation today.',
        'At the same time, Visser believes bond market anxiety is overstated, that the fundamentals for stocks remain strong, and that the AI trade is consolidating rather than collapsing.',
        'The big question, therefore, is not just how fast AI keeps developing. It is what happens when AI itself starts becoming an economic actor.'
      ]
    },
    disclaimer: 'AI-sammanfattning baserad på videons transkribering. Kan innehålla fel. Åsikterna tillhör Jordi Visser, inte NTM, och detta är inte finansiell rådgivning. Se originalvideon för fullständigt sammanhang.'
  }
];