const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const raw=require('../docs/internal/knowledge/catalog.cjs'),Core=require('../knowledge-core.js'),Q=require('../scripts/knowledge_quality.cjs'),rules=require('../data/rule-registry.json'),K=Core.create(raw),clone=structuredClone;
test('Knowledge100 labeled retrieval benchmark has no wrong confident matches or other failures',()=>{const result=require('../scripts/knowledge_benchmark.cjs').run();assert.deepEqual(result.failures,[]);assert.equal(result.wrongConfidentMatch,0);});
test('V2 also preserves every positive Wave1 exact/alias fixture',()=>{for(const [q,id] of require('./fixtures/wave1-queries.json'))if(id)assert.equal(K.respond(q).answerId,id,q);});
test('formula is bounded, independently checked, unit/period explicit and never evaluated as code',()=>{
 for(const [price,eps,expected] of [[150,6,25],[80,4,20],[123.45,2.5,49.38]]){const r=K.calculate('pe',{price,eps,currency:'SEK',period:'annual'});assert.equal(r.kind,'ANSWER');assert.ok(Math.abs(r.calculation.value-expected)<1e-10);}
 const base={price:150,eps:6,currency:'SEK',period:'annual'};
 for(const patch of [{eps:0},{price:-1},{eps:Infinity},{eps:1e-320},{price:'150'},{currency:'SEK/USD'},{period:'quarter'},{expression:'alert(1)'},{price:1e13}])assert.equal(K.calculate('pe',{...base,...patch}).kind,'INVALID_INPUT');
 assert.equal(K.calculate('pe',{...base,eps:-6}).calculation.value,null);assert.equal(K.calculate('eps',base).kind,'ABSTAIN_NO_COVERAGE');
});
test('safe projection excludes editorial history/private nested notes and bodies from compact index',()=>{
 const data=clone(raw);data.entries[0].history=[{reason:'PRIVATE'}];data.entries[0].sections.inline.secret='PRIVATE';data.entries[0].sources[0].internalNotes='PRIVATE';
 assert.ok(!JSON.stringify(Core.project(data)).includes('PRIVATE'));const index=Core.index(data);assert.ok(index.entries.every(e=>!e.fullAnswer&&!e.sources&&!e.example&&!e.caveats));assert.equal(index.entries.length,raw.entries.filter(Core.visible).length);assert.equal(index.entries.filter(e=>require('../docs/internal/knowledge/scale.cjs').baselineIds.includes(e.id)).length,29);
 const staged=vm.createContext({});vm.runInContext(fs.readFileSync('knowledge-core.js','utf8'),staged);vm.runInContext(fs.readFileSync('knowledge-catalog.js','utf8'),staged);assert.equal(staged.NTMKnowledgeCatalog.compact,true);
 for(const e of index.entries){const p=JSON.parse(fs.readFileSync('data/knowledge/answers/'+e.id+'.json'));assert.equal(p.contentVersion,e.contentVersion);assert.equal(p.question,e.question);assert.ok(p.fullAnswer);assert.ok(!JSON.stringify(p).includes('internalReview'));}
});
test('stale policy suppresses rule answers at runtime without refreshing reviews',async()=>{const data=clone(raw),e=data.entries.find(e=>e.id==='isk');e.reviewDue='2000-01-01';const k=Core.create(data);assert.equal(k.respond(e.question).kind,'ABSTAIN_NO_COVERAGE');assert.equal(await k.explain('isk','knowledge'),null);assert.equal(k.entries.find(e=>e.id==='isk').reviewedAt,e.reviewedAt);});
test('shared context modes accept public IDs only and do not expose full answer in compact/reminder',async()=>{for(const context of ['research','calculator','macro','public-report','academy-reminder']){const compact=await K.explain('pe',context,'compact');assert.equal(compact.excerpt,K.entries.find(e=>e.id==='pe').shortAnswer);assert.equal(compact.fullAnswer,undefined);}assert.equal(await K.explain('pe','private-thesis'),null);assert.equal(await K.explain('private contents','research'),null);assert.ok((await K.explain('pe','research','full')).fullAnswer);});
test('validator rejects missing references, unknown typed fields, alias collisions, source hazards and merge loops',()=>{
 const mutations=[d=>d.entries[0].period='2026-99-99',d=>d.entries[0].jurisdiction='missing',d=>d.entries.find(e=>e.id==='isk').period='2027',d=>d.entries[0].conceptRefs=['missing'],d=>d.entries[0].intent='advice',d=>d.entries[0].relatedAnswers=[{id:'missing',type:'deeper'}],d=>d.entries[0].sections.formula.template='eval',d=>d.entries[0].sections.inline.expression='alert(1)',d=>d.entries[0].aliases.push(d.entries[1].aliases[0]),d=>d.entries[0].aliases=['<script>'],d=>d.entries[0].fullAnswer='a'.repeat(25000),d=>d.entries[0].sources[0].url='https://secret:pass@example.org',d=>d.entries[0].contentVersion=2,d=>d.merges=[{fromId:'a',fromSlug:'a',toId:'b',reason:'x',reviewer:'x',date:'2026-09-19'},{fromId:'b',fromSlug:'b',toId:'a',reason:'x',reviewer:'x',date:'2026-09-19'}]];
 for(const mutate of mutations){const d=clone(raw);mutate(d);assert.ok(Q.validate(d,rules).length,mutate.toString());}
});
test('new substantive draft requires actual claim evidence and explicit approval before public projection',()=>{
 const e=require('../scripts/knowledge_editorial.cjs').template('definition','sample-definition'),d=clone(raw);d.entries.push(e);assert.deepEqual(Q.validate(d,rules),[]);assert.ok(!Core.project(d).entries.some(x=>x.id===e.id));e.status='reviewed';assert.ok(Q.validate(d,rules).some(x=>x.includes('Unapproved')));
});
test('draft-only retrieval aliases, pilot labels and concepts never enter a public index',()=>{const d=clone(raw),e=d.entries[0];e.status='draft';e.conceptRefs=['private-draft-concept'];d.knowledgeConcepts.push({id:'private-draft-concept',term:'PRIVATE-CONCEPT',category:'valuation',synonyms:[],abbreviations:[],related:[]});d.retrieval.aliases.push({query:'PRIVATE-ALIAS',answerId:e.id});d.retrieval.typos.push({query:'PRIVATE-TYPO',answerId:e.id});d.retrieval.clarifications.push({query:'PRIVATE-CLARIFICATION',answerIds:[e.id]});d.pilotConcepts.push({id:'draft-pilot',title:'PRIVATE-PILOT',answerId:e.id,excerpt:'shortAnswer'});assert.ok(!JSON.stringify(Core.index(d)).includes('PRIVATE'));});
test('typo ambiguity clarifies rather than selecting a nearby answer',()=>{const d=clone(raw);d.entries.find(e=>e.id==='eps').aliases.push('safetermx');d.entries.find(e=>e.id==='fcf').aliases.push('safetermz');const r=Core.create(d).respond('safetermy');assert.equal(r.kind,'CLARIFY');assert.deepEqual(r.choices.sort(),['eps','fcf']);});
test('substantive history audit detects edits but retrieval configuration changes do not alter content',()=>{const h=require('../scripts/knowledge_history.cjs'),baseline=require('../docs/internal/knowledge/history-baseline.json'),d=clone(raw);d.retrieval.version++;assert.deepEqual(h.audit(d,baseline),[]);d.entries[0].fullAnswer+=' Changed conclusion.';assert.ok(h.audit(d,baseline).length);d.entries[0].contentVersion++;d.entries[0].history=[{from:1,to:2,reason:'Corrected source interpretation',reviewer:'test-only',date:'2026-09-19'}];assert.deepEqual(h.audit(d,baseline),[]);d.entries[0].contentVersion=3;d.entries[0].history.push({from:2,to:3,reason:'Second correction',reviewer:'test-only',date:'2026-09-19'});assert.deepEqual(h.audit(d,baseline),[]);const typed=clone(raw);typed.entries.find(e=>e.id==='forward').sections.comparison.axes[0].left='Different financial claim';assert.ok(h.audit(typed,baseline).length);const added=clone(raw.entries[0]);added.id='future-answer';added.status='draft';d.entries.push(added);assert.deepEqual(h.audit(d,baseline),[]);added.status='reviewed';assert.ok(h.audit(d,baseline).some(e=>e.includes('new answer baseline')));});
test('all five local authoring examples validate as drafts and remain out of public pages',()=>{const A=require('../scripts/knowledge_editorial.cjs');for(const kind of ['definition','formula','comparison','interpretation','sensitive']){const e=A.template(kind,'demo-'+kind),d=clone(raw);d.entries.push(e);assert.deepEqual(Q.validate(d,rules),[],kind);assert.ok(!Core.project(d).entries.some(x=>x.id===e.id));}const d=clone(raw),e=A.template('definition','new-definition');e.editorial.approval='inherited-not-independent';d.entries.push(e);assert.ok(Q.validate(d,rules).some(x=>x.includes('cannot inherit')));});
test('synthetic generation is explicitly test-only and pagination never embeds the inventory',()=>{const data=require('../scripts/knowledge_scale.cjs').fixture(100),B=require('../scripts/build_knowledge.cjs');assert.throws(()=>B.build(data),/Synthetic/);const result=B.build(data,{synthetic:true});assert.equal((result.pages.get('fragor-svar.html').match(/data-knowledge-card=/g)||[]).length,0);assert.ok([...result.pages.keys()].some(k=>/omrade-.*-2/.test(k)));});
test('seed migration preserves explicit future editorial metadata instead of resetting reviews or relationships',()=>{const e=clone(raw.entries[0]);e.editorial={owner:'fixture-reviewer',approval:'accepted'};e.sources[0].authority='primary';e.sources[0].supports=['shortAnswer'];e.relatedAnswers=[];e.reviewedAt='2026-09-18';const data=require('../docs/internal/knowledge/scale.cjs').extend({version:1,categories:raw.categories,entries:[e],pilotConcepts:[]});assert.equal(data.entries[0].editorial.approval,'accepted');assert.equal(data.entries[0].sources[0].authority,'primary');assert.deepEqual(data.entries[0].sources[0].supports,['shortAnswer']);assert.equal(data.entries[0].reviewedAt,'2026-09-18');assert.deepEqual(data.entries[0].relatedAnswers,[]);});
test('explicit merge retains a navigable old URL while rejecting target chains',()=>{const d=clone(raw);d.merges=[{fromId:'retired-definition',fromSlug:'retired-definition',toId:'pe',reason:'Reviewed duplicate',reviewer:'test-only',date:'2026-09-19'}];assert.deepEqual(Q.validate(d,rules),[]);const page=require('../scripts/build_knowledge.cjs').build(d).pages.get('fragor-svar-retired-definition.html');assert.ok(page.includes('href="fragor-svar-pe-tal.html"'));d.merges[0].toId='another-retired-id';assert.ok(Q.validate(d,rules).length);});
test('lazy load deduplicates requests, omits credentials and rejects mixed deployment versions',async()=>{
 const context=vm.createContext({fetch:async(url,options)=>{assert.equal(options.credentials,'omit');context.calls++;return {ok:true,json:async()=>JSON.parse(fs.readFileSync(url,'utf8'))};},calls:0});vm.runInContext(fs.readFileSync('knowledge-core.js','utf8'),context);context.input=Core.index(raw);vm.runInContext('k=NTMKnowledgeCore.create(input)',context);await Promise.all([context.k.load('pe'),context.k.load('pe')]);assert.equal(context.calls,1);await context.k.load('pe');assert.equal(context.calls,1);
 const broken=Core.index(raw);broken.entries.find(e=>e.id==='eps').contentVersion=99;context.input=broken;vm.runInContext('k=NTMKnowledgeCore.create(input)',context);await assert.rejects(context.k.load('eps'),/version mismatch/);
});
