const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(ticker='NVDA',date='2026-08-01'){
 const w={};w.window=w;vm.createContext(w);
 for(const f of ['company-capital','company-observations','company-segments','company-insiders','company-ownership','company-material-events','company-evidence','research-snapshot','change-detection','research-since'])vm.runInContext(fs.readFileSync(f+'.js','utf8'),w);
 const feed=JSON.parse(fs.readFileSync(`data/stocks/evidence/${ticker}.json`)),stock=JSON.parse(fs.readFileSync(`data/stocks/${ticker}.json`));
 const thesis={latestRevisionId:'saved',revisions:[{id:'saved',savedAt:date,text:'PRIVATE_SENTINEL'}]};
 const args={thesis,stock,feed,until:'2026-09-24'};return {w,args,run:()=>w.NTMResearchSince.build(args)};
}
test('no revision and no new reviewed evidence are distinct',()=>{const {args,run}=setup();args.thesis=null;assert.equal(run().state,'no_revision');args.thesis={latestRevisionId:'new',revisions:[{id:'new',savedAt:'2026-09-24'}]};assert.equal(run().groups.length,0);});
test('real reviewed reporting, guidance, segment, capital, Form 4, ownership and events',()=>{const {run}=setup('NVDA','2024-01-01');const m=run();for(const id of ['reporting','guidance','business','capital','owners','events'])assert(m.groups.some(g=>g.id===id),id);assert(m.groups.find(g=>g.id==='owners').rows.some(r=>r.label==='4'));assert(m.groups.find(g=>g.id==='owners').rows.some(r=>/13[DG].*\/A/.test(r.label)));});
test('KPI changes use reviewed comparison API',()=>{const {run}=setup('SOFI','2026-01-01');assert(run().groups.find(g=>g.id==='business').rows.some(r=>r.comparison.comparable));});
test('late ingestion and same-day publication cannot create changes',()=>{const {args,run}=setup('NVDA','2026-09-24');args.feed.verifiedAt='2026-09-25';assert.equal(run().groups.length,0);});
test('pending evidence excluded and unreviewed canonical rows fail closed',()=>{const {args,run}=setup();const before=JSON.stringify(run());args.feed.reviewedEvidence.pendingReview.push({label:'PRIVATE_PENDING',publicationDate:'2026-09-22'});assert.equal(JSON.stringify(run()),before);args.feed.reviewedEvidence.observations[0].review.status='review_required';assert.throws(run);});
test('updater failure preserves verified comparison; failed feed is not canonical',()=>{const {args,run}=setup();const before=JSON.stringify(run().groups);args.unavailable=true;assert.equal(JSON.stringify(run().groups),before);args.feed.status='unavailable';assert.equal(run().state,'unavailable');});
test('new saved revision is baseline, history is immutable and private prose absent',()=>{const {args,run}=setup();const old=JSON.stringify(args.thesis.revisions[0]);assert(run().groups.length);args.thesis.revisions.push({id:'later',savedAt:'2026-09-24'});args.thesis.latestRevisionId='later';assert.equal(run().groups.length,0);assert.equal(JSON.stringify(args.thesis.revisions[0]),old);assert(!JSON.stringify(run()).includes('PRIVATE_SENTINEL'));});
test('many observations compress into seven or fewer unique areas without empty groups',()=>{const {run}=setup('NVDA','2024-01-01');const m=run();assert(m.groups.reduce((n,g)=>n+g.rows.length,0)>50);assert(m.groups.length<=7);assert.equal(new Set(m.groups.map(g=>g.id)).size,m.groups.length);assert(m.groups.every(g=>g.rows.length));});
test('definition breaks never manufacture a delta',()=>{const {args,run}=setup('SOFI','2026-01-01');const k=args.feed.reviewedEvidence.observations.filter(o=>o.kind==='kpi').at(-1);k.definitionVersion='changed';const r=run().groups.find(g=>g.id==='business').rows.find(r=>r.label===k.label&&r.date===k.publicationDate);assert.equal(r.comparison.comparable,false);assert.equal(r.comparison.changePercent,undefined);});
test('financial changes require actual new publication dates and use snapshot gates',()=>{const {w,args,run}=setup();const snap=w.NTMResearchSnapshot.fromStockData(args.stock);snap.ticker='NVDA';snap.ttmMetrics.revenue*=.8;args.thesis.revisions[0].valuationSnapshot=snap;assert(run().groups.find(g=>g.id==='financials').rows.some(r=>r.label==='Intäkter · TTM'));args.thesis.revisions[0].savedAt='2026-09-24';assert(!run().groups.some(g=>g.id==='financials'));});
test('adapter and UI cannot transmit private Research',()=>{for(const f of ['research-since.js','research-since-ui.js'])assert(!/fetch\(|XMLHttpRequest|sendBeacon|localStorage\.setItem|\.innerHTML\s*=/.test(fs.readFileSync(f,'utf8')));});
