const fs=require('node:fs'),path=require('node:path');
const raw=require('../docs/internal/knowledge/catalog.cjs'),Core=require('../knowledge-core.js'),R=require('../ntm-relations.js');
const root=path.resolve(__dirname,'..'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function build(input=raw,options={}){
 if(input.synthetic&&!options.synthetic)throw new Error('Synthetic catalogs require explicit in-memory test generation');
 const K=Core.create(input);
 const registry=JSON.parse(fs.readFileSync(path.join(root,'data/rule-registry.json'),'utf8'));
 const errors=require('./knowledge_quality.cjs').validate(input,registry);if(errors.length)throw new Error(errors.join('\n'));
 const catalog=R.catalog([]),entity=id=>catalog.entities.find(e=>e.id===id);
 const link=(id,label,extra='')=>{const answer=id.startsWith('knowledge-')&&K.entries.find(e=>e.id===id.slice(10)),e=answer?{url:K.url(answer.id),title:answer.question}:entity(id);if(!e?.url)throw new Error('Unknown knowledge destination '+id);return `<a href="${esc(e.url)}" ${extra}>${esc(label||e.title)}</a>`;};
 const shell=fs.readFileSync(path.join(root,'min-ntm.html'),'utf8').match(/<body[^>]*>([\s\S]*?)<main\b/)[1].replace('brand-subtitle">Min NTM','brand-subtitle">Frågor &amp; svar');
 const page=(title,description,body,answer=false)=>`<!DOCTYPE html>\n<html lang="sv"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>${esc(title)} | NTM Frågor &amp; svar</title><meta name="description" content="${esc(description)}" /><link rel="stylesheet" href="style.css" /><link rel="stylesheet" href="premium.css" /><link rel="stylesheet" href="knowledge.css" /><link rel="stylesheet" href="wave1.css" /><link rel="stylesheet" href="visual-v3-tokens.css" /></head><body class="visual-v3">${shell}<main id="main-content" class="container knowledge-shell" tabindex="-1">${body}</main><script src="knowledge-core.js"></script><script src="knowledge-catalog.js"></script><script src="ntm-product.js"></script><script src="valuation-core.js"></script><script src="script.js"></script><script src="knowledge-ui.js"></script><script src="wave1-context.js"></script><script src="wave1-ui.js"></script><script src="ntm-ui.js"></script></body></html>\n`;
 const categories=K.categories,category=id=>categories.find(c=>c.id===id).title;
 const pages=new Map();
 pages.set('fragor-svar.html',page('Frågor & svar om investeringar','Korta svar på vanliga frågor om investeringar. Förstå P/E, EPS, avkastning, valuta och risk med exempel, källor och nästa steg i NTM.',
 `<header class="knowledge-hero"><p class="section-kicker">NTM Kunskapsbank</p><h1>Frågor &amp; svar</h1><p>Ett tydligt svar på en konkret fråga. Här hittar du förklaringar, enkla exempel och det viktigaste att tänka på.</p><p class="note">Redaktionellt framtagna grundfrågor, inte inskickade användarfrågor. Vill du följa en lärväg? <a href="academy.html" data-knowledge-related>Öppna Academy</a>.</p></header>
 <section aria-labelledby="find-answer"><h2 id="find-answer">Hitta ditt svar</h2><div class="knowledge-controls" data-knowledge-controls hidden><label for="knowledgeSearch">Sök fråga eller begrepp<input id="knowledgeSearch" type="search" maxlength="160" placeholder="Till exempel vinst per aktie" /></label><label for="knowledgeCategory">Område<select id="knowledgeCategory"><option value="">Alla områden</option>${categories.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select></label><button type="button" id="knowledgeClear" class="secondary-btn">Rensa filter</button></div><nav class="knowledge-categories" aria-label="Frågeområden">${categories.map(c=>`<a href="#category-${c.id}" data-knowledge-category="${c.id}">${esc(c.title)}</a>`).join('')}</nav><p id="knowledgeResults" role="status">${K.publicEntries().length} svar</p><p id="knowledgeEmpty" hidden>Inga svar matchar. Prova ett kortare begrepp eller välj ett annat område.</p></section>
 <section data-knowledge-featured aria-labelledby="core-questions"><h2 id="core-questions">Kärnfrågor att börja med</h2><ul class="knowledge-featured">${K.publicEntries().filter(e=>e.featured).slice(0,6).map(e=>`<li>${link('knowledge-'+e.id)}</li>`).join('')}</ul></section>
 <section aria-labelledby="answers"><h2 id="answers">Alla frågor</h2><div id="knowledgeList">${categories.map(c=>`<section data-knowledge-group="${c.id}" aria-labelledby="category-${c.id}"><h3 id="category-${c.id}">${esc(c.title)}</h3><div class="knowledge-list">${K.publicEntries().filter(e=>e.category===c.id).map(e=>`<article data-knowledge-card="${e.id}"><h4>${link('knowledge-'+e.id)}</h4><p>${esc(e.shortAnswer)}</p></article>`).join('')}</div></section>`).join('')}</div></section><noscript><p>Alla frågor och svar går att läsa utan JavaScript. Sökning och filtrering kräver JavaScript; områdeslänkarna tar dig till respektive lista.</p></noscript>`));
 for(const e of K.publicEntries()){
  const rows=R.query(catalog,'knowledge-'+e.id,{limit:20}),lessonRows=rows.filter(r=>r.to.startsWith('learn-')),toolRows=rows.filter(r=>!r.to.startsWith('learn-'));
  let rule='';if(e.ruleId){const r=registry.rules.find(r=>r.id===e.ruleId);rule=`<p class="note" data-rule-registry="${esc(r.id)}">Aktuella årsparametrar: ${link('tool-tax','ISK-kalkylatorn')}. Regelversion ${esc(r.effectiveFrom)}, källkontrollerad ${esc(r.lastVerified)}, nästa granskning ${esc(r.nextReview)}. <a href="${esc(r.source)}">Skatteverkets underlag för inkomstår ${r.effectiveYear}</a>.</p>`;}
  pages.set(K.url(e.id),page(e.question,e.shortAnswer,
   `<article class="knowledge-answer" data-knowledge-answer="${e.id}"><nav aria-label="Brödsmulor"><a href="fragor-svar.html">Frågor &amp; svar</a> / <a href="fragor-svar.html#category-${e.category}">${esc(category(e.category))}</a></nav><p class="section-kicker">${esc(category(e.category))} · ${{beginner:'Grund',intermediate:'Fördjupning',advanced:'Avancerat'}[e.difficulty]}</p><h1>${esc(e.question)}</h1><section class="knowledge-short"><h2>Kort svar</h2><p>${esc(e.shortAnswer)}</p></section><h2>Förklaring</h2><p>${esc(e.fullAnswer)}</p>${e.example?`<section class="knowledge-example"><h2>Exempel — förenklat</h2><p>${esc(e.example)}</p></section>`:''}<h2>Viktigt att tänka på</h2><p>${esc(e.caveats)}</p>${rule}
   <section class="knowledge-related" aria-labelledby="learn-more"><h2 id="learn-more">Lär dig mer i Academy</h2>${e.practiceId?`<p><a href="academy-activity-${esc(e.practiceId)}.html" data-knowledge-related>Pröva begreppet i en befintlig övning</a></p>`:''}<ul>${lessonRows.map(r=>`<li>${link(r.to,null,`data-knowledge-related data-relation-id="${r.id}"`)}</li>`).join('')}</ul></section><section class="knowledge-related" aria-labelledby="ntm-tools"><h2 id="ntm-tools">Relaterat i NTM</h2><ul>${toolRows.map(r=>`<li>${link(r.to,null,`data-knowledge-related data-relation-id="${r.id}"`)}</li>`).join('')}</ul></section>
   <details class="knowledge-method"><summary>Källor och metod</summary><p>Granskat ${esc(e.reviewedAt)}. Redaktionell grundfråga, inte en inskickad användarfråga. Definitioner stöds av källorna nedan. Exempel och resonemang är NTM:s pedagogiska illustrationer; tumregler är inte garantier eller personliga investeringsråd.</p><ul>${e.sources.map(s=>`<li><a href="${esc(s.url)}">${esc(s.title)}</a> · kontrollerad ${esc(s.reviewedAt)}</li>`).join('')}</ul></details><nav class="knowledge-bottom" aria-label="Fortsätt läsa"><a href="fragor-svar.html">Alla frågor och svar</a><a href="academy.html" data-knowledge-related>Följ en lärväg i Academy</a></nav></article>`,true));
 }
 for(const e of K.entries){let html=pages.get(K.url(e.id)),extra='';if(e.sections?.comparison){const c=e.sections.comparison;extra+=`<section><h2>Jämförelse</h2><table><caption>${esc(e.question)}</caption><thead><tr><th scope="col">Aspekt</th><th scope="col">${esc(c.leftLabel||"Begrepp A")}</th><th scope="col">${esc(c.rightLabel||"Begrepp B")}</th></tr></thead><tbody>${c.axes.map(a=>`<tr><th scope="row">${esc(a.label)}</th><td>${esc(a.left)}</td><td>${esc(a.right)}</td></tr>`).join('')}</tbody></table><p>${esc(c.limitations)}</p></section>`;}if(e.relatedAnswers?.length)extra+=`<section><h2>Relaterade frågor</h2><ul>${e.relatedAnswers.filter(r=>K.url(r.id)).map(r=>`<li><a href="${K.url(r.id)}">${esc(K.entries.find(a=>a.id===r.id).question)}</a></li>`).join('')}</ul></section>`;pages.set(K.url(e.id),html.replace('<details class="knowledge-method">',extra+'<details class="knowledge-method">'));}
 // Static category pages provide bounded, crawlable no-JS access. No synthetic answers.
 for(const c of categories){const answers=K.publicEntries().filter(e=>e.category===c.id);for(let offset=0;offset<answers.length;offset+=12){const number=offset/12+1,name=`fragor-svar-omrade-${c.id}-${number}.html`;pages.set(name,page(c.title+' – frågor och svar','Granskade frågor inom '+c.title.toLowerCase()+'.',`<h1>${esc(c.title)}</h1><p><a href="fragor-svar.html">Frågor &amp; svar</a></p><ul>${answers.slice(offset,offset+12).map(e=>`<li><a href="${K.url(e.id)}">${esc(e.question)}</a></li>`).join('')}</ul>${offset+12<answers.length?`<a href="fragor-svar-omrade-${c.id}-${number+1}.html">Nästa sida</a>`:''}`));}}
 let landing=pages.get('fragor-svar.html');
 // Do not ship the entire answer inventory in the initial HTML.
 landing=landing.replace(/<section data-knowledge-group="([^"]+)"[\s\S]*?<\/section>/g,(_,id)=>`<section data-knowledge-group="${id}" aria-labelledby="category-${id}"><h3 id="category-${id}">${esc(category(id))}</h3><div class="knowledge-list"><a href="fragor-svar-omrade-${id}-1.html">Utforska ${esc(category(id).toLowerCase())}</a></div></section>`).replace('Alla frågor</h2>','Utforska områden</h2>');
 pages.set('fragor-svar.html',landing);
 for(const m of input.merges||[]){const target=K.url(m.toId);pages.set('fragor-svar-'+m.fromSlug+'.html',page('Svaret har flyttat','Den här granskade frågan har slagits samman med ett annat svar.',`<h1>Svaret har flyttat</h1><p><a href="${target}">Öppna det granskade svaret</a></p>`));}
 const payloads=new Map(Core.project(input).entries.map(e=>['data/knowledge/answers/'+e.id+'.json',JSON.stringify(e)+'\n']));
 const serialized=JSON.stringify(Core.index(input)).replace(/</g,'\\u003c');
 const script=`/* Generated compact index. Answer bodies are loaded on demand. */\n(function(root){const core=typeof module!=='undefined'?require('./knowledge-core.js'):root.NTMKnowledgeCore;const api=typeof module!=='undefined'?require('./scripts/knowledge_source.cjs'):core.create(${serialized});root.NTMKnowledgeCatalog=api;if(typeof module!=='undefined')module.exports=api;})(typeof window!=='undefined'?window:globalThis);\n`;
 return {pages,script,payloads};
}
module.exports={build};
