// Static, indexable lessons from one reviewed catalog. Called by build_seo.cjs.
const fs=require('node:fs'),path=require('node:path');
const A=require('../academy-catalog.js'),R=require('../ntm-relations.js');
const root=path.resolve(__dirname,'..');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function pages(){
  const errors=require('./academy_quality.cjs').validate(A,JSON.parse(fs.readFileSync(path.join(root,'docs/internal/academy/knowledge-bank.json'),'utf8')));
  errors.push(...require('./academy_v3_quality.cjs').validate());
  if(errors.length)throw new Error(errors.join('\n'));
  const shell=fs.readFileSync(path.join(root,'min-ntm.html'),'utf8').match(/<body>([\s\S]*?)<main\b/)[1].replace('brand-subtitle">Min NTM','brand-subtitle">Academy');
  const catalog=R.catalog([]),entity=id=>catalog.entities.find(e=>e.id===id);
  const link=(id,text,extra='')=>{const e=entity(id);if(!e?.url)throw new Error('Unknown Academy destination '+id);return `<a href="${esc(e.url)}" ${extra}>${esc(text||e.title)}</a>`;};
  const progress=`<section class="academy-progress" aria-label="Din lärhistorik"><p data-academy-progress>0 av ${A.published().length} lektioner klara — 0 %</p><progress data-academy-bar value="0" max="${A.published().length}" aria-label="Avklarade lektioner"></progress><a data-academy-continue href="${A.url('aktier')}">Börja här: Vad är en aktie?</a><p class="note">Sparas i den här webbläsaren. Inget konto behövs. <a href="min-ntm.html#localDataDepth">Säkerhetskopiera dina framsteg</a>.</p></section>`;
  function page(title,description,body){return `<!DOCTYPE html>\n<html lang="sv"><head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>${esc(title)} | NTM Academy</title><meta name="description" content="${esc(description)}" /><link rel="stylesheet" href="style.css" /><link rel="stylesheet" href="premium.css" /><link rel="stylesheet" href="academy.css" /></head><body>${shell}<main id="main-content" class="container academy-shell" tabindex="-1">${body}<p id="academyStatus" role="status" aria-live="polite"></p><noscript><p>Du kan läsa alla lektioner och följa länkarna utan JavaScript. Lokal progress, sökning och kunskapsfrågor kräver JavaScript.</p></noscript></main><script src="academy-catalog.js"></script><script src="academy-activities.js"></script><script src="academy-progress.js"></script><script src="academy-progression.js"></script><script src="ntm-product.js"></script><script src="valuation-core.js"></script><script src="script.js"></script><script src="academy-ui.js"></script><script src="academy-v3-ui.js"></script><script src="ntm-ui.js"></script></body></html>\n`;}
  const v3=require('./build_academy_v3.cjs').render({A,link,esc,page});
  const result=new Map(v3.pages);
  const level=l=>({beginner:'Grund',intermediate:'Fördjupning',advanced:'Avancerat'}[l.difficulty]);
  result.set('academy.html',page('Lär dig investera, ett begrepp i taget',`Lär dig aktier, sparande, nyckeltal, värdering och makro i ${A.published().length} praktiska lektioner. Följ ett spår eller välj fritt. Din lärhistorik sparas lokalt.`,
    `<header class="academy-hero"><p class="academy-eyebrow">NTM Academy · ditt läranderum</p><h1>Förstå en sak.<br />Pröva den direkt.</h1><p>Lär dig grunderna i din takt. Börja enkelt, öppna fördjupningen när du vill och ta nästa steg i ett NTM-verktyg.</p><nav class="academy-next" aria-label="Hitta i Academy"><a href="#lessons">Sök eller välj ämne</a><a href="#paths">Se lärspåren</a></nav></header>${v3.home}${progress}
    <p data-academy-start><a class="primary-btn" data-academy-path="beginner" href="${A.url('aktier')}?path=beginner">Ny här? Börja med grunderna</a></p>
    <section data-academy-recent hidden aria-labelledby="recent"><h2 id="recent">Senast klara</h2><ul data-recent-list></ul></section>
    <section aria-labelledby="paths"><h2 id="paths">Välj ett spår — eller din egen väg</h2><p>Inga låsta lektioner, provkrav eller tidsgränser. Grund ger en start, Fördjupning kopplar ihop begrepp och Avancerat prövar modellernas gränser.</p><div class="academy-grid academy-paths">${A.paths.map(p=>`<article class="card"><h3>${esc(p.title)}</h3><p>${esc(p.goal)}</p><p data-path-progress="${p.id}">0 av ${p.lessons.length} klara</p><details><summary>Se spårets lektioner och mål</summary><ol>${p.lessons.map(id=>`<li>${link('learn-'+id,null,`data-path-lesson="${p.id}"`)} <span data-academy-status="${id}">Inte påbörjad</span></li>`).join('')}</ol><p>${esc(p.endpoint)}</p></details><a class="secondary-btn" data-academy-path="${p.id}" href="${A.url(p.lessons[0])}?path=${p.id}">Börja spåret</a><div data-path-end="${p.id}" hidden><p>${esc(p.endpoint)}</p>${link(p.entity,'Pröva i NTM','data-academy-tool')} · <a href="${A.url(A.paths.find(n=>n.id===p.nextPath).lessons[0])}?path=${p.nextPath}" data-academy-path="${p.nextPath}">Nästa spår</a></div></article>`).join('')}</div></section>
    <section aria-labelledby="map"><h2 id="map">Din lärandekarta</h2><div class="academy-grid">${A.categories.map(c=>`<article class="card"><h3><a href="?category=${c.id}#lessons" data-category-select="${c.id}">${esc(c.title)}</a></h3><p>${esc(c.description)}</p><p data-category-progress="${c.id}">0 av ${A.published().filter(l=>l.category===c.id).length} klara</p></article>`).join('')}</div></section>
    <section aria-labelledby="lessons"><h2 id="lessons">Alla lektioner</h2><div class="academy-filter"><label>Sök titel eller begrepp<input id="academySearch" type="search" placeholder="Till exempel vinst per aktie" /></label><label>Område<select id="academyCategory"><option value="">Alla områden</option>${A.categories.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select></label></div><p id="academyCategoryDescription">Välj område eller sök. Lektionerna går från grunder till tillämpning.</p><p id="academyResults" role="status">${A.published().length} lektioner visas</p><div class="academy-list">${A.published().map(l=>`<article data-lesson-card="${l.id}"><div><span class="academy-eyebrow">${esc(A.categories.find(c=>c.id===l.category).title)} · ${level(l)}</span><h3>${link('learn-'+l.id)}</h3><p>${esc(l.summary)}</p></div><span data-academy-status="${l.id}">Inte påbörjad</span></article>`).join('')}</div></section>`));
  for(const l of A.published()){
    const s=l.sections;
    const faqs=R.query(catalog,'learn-'+l.id,{type:'related',limit:5}).filter(r=>r.to.startsWith('knowledge-')).slice(0,4);
    const faqSection=faqs.length?'<details><summary>Vanliga frågor</summary><ul>'+faqs.map(r=>'<li>'+link(r.to)+'</li>').join('')+'</ul></details>':'';
    const practice=require('../academy-activities.js').published().filter(o=>o.relatedConcepts.includes(l.id)).slice(0,3).map(o=>link('activity-'+o.id)).join(' ');
    const tool=l.relatedEntityIds.map(id=>link(id,'Testa: '+entity(id).title,'data-academy-tool class="secondary-btn"')).join(' ');
    const references=l.references.map(r=>`<li><a href="${esc(r.url)}">${esc(r.title)}</a> · kontrollerad ${r.reviewedAt}</li>`).join('');
    let rule='';if(l.ruleId){const registry=JSON.parse(fs.readFileSync(path.join(root,'data/rule-registry.json'),'utf8'));if(!JSON.stringify(registry).toLowerCase().includes('isk'))throw new Error('Missing ISK rules');rule='<p data-rule-registry="isk">Årsreglerna kommer från NTM:s <a href="data/rule-registry.json">daterade regelregister</a>. Välj inkomstår i ISK-kalkylen; årets procentsats hårdkodas inte i lektionen.</p>';}
    result.set(A.url(l.id),page(l.title,l.summary,`<article class="academy-lesson" data-academy-lesson="${l.id}"><nav aria-label="Brödsmulor"><a href="academy.html">Academy</a> / <a href="academy.html?category=${l.category}#lessons">${esc(A.categories.find(c=>c.id===l.category).title)}</a></nav><p class="academy-eyebrow">${level(l)} · läs och pröva</p><h1>${esc(l.title)}</h1><span data-academy-status="${l.id}">Inte påbörjad</span><h2>Kort svar</h2><p class="academy-short">${esc(l.summary)}</p><h2>Varför spelar det roll?</h2><p>${esc(s.why)}</p><section class="academy-example"><h2>Exempel — förenklat</h2><p>${esc(s.example)}</p></section><details><summary>Fördjupa: samband och begränsningar</summary><p>${esc(s.deep)}</p>${l.extension?`<h3>${esc(l.extension.title)}</h3><p>${esc(l.extension.example)}</p><p>${esc(l.extension.interpretation)}</p>`:""}</details><h2>Vanliga misstag</h2><p>${esc(s.mistake)}</p><h2>Testa själv</h2><p>${esc(s.exercise)}</p><div class="academy-next">${tool}</div>
    ${l.quiz.map((q,i)=>`<form class="academy-quiz" data-quiz="${i}"><fieldset><legend>Fundera en stund: ${esc(q.question)}</legend>${q.options.map((o,n)=>`<label><input type="radio" name="answer" value="${n}" />${esc(o)}</label>`).join('')}</fieldset><button type="submit" class="secondary-btn">Visa förklaring</button><p role="status"></p><p class="note">Frivilligt. Svarstext sparas inte. Kontrollens utfall sparas lokalt, ger XP en gång och påverkar inte om du kan markera lektionen som klar.</p></form>`).join('')}
    <nav class="academy-related" aria-label="Praktiska aktiviteter">${practice}</nav>${faqSection}<h2>Relaterade begrepp</h2><div class="academy-related">${l.relatedConcepts.map(id=>link('learn-'+id)).join('')}</div><details><summary>Källa och metod</summary><p>${esc(l.method)}</p><p>Innehåll granskat ${l.reviewedAt}.</p>${references?'<ul>'+references+'</ul>':''}${rule}<p>Definitionen förklarar begreppet. Räkneexemplen visar en metod. Tumregler är inte lagar; framtida tillväxt och avkastningskrav är egna antaganden.</p></details><div class="academy-next"><button type="button" data-academy-complete disabled aria-pressed="false" class="primary-btn">Markera som klar</button><p id="academyPathState" role="status"></p><a id="academyPathPrevious" hidden href="academy.html#roadmap">Föregående lektion</a><a id="academyPathNext" hidden href="academy.html#paths">Nästa i spåret</a><a href="academy.html#lessons">Till lärandekartan</a></div>${progress}${v3.summary}</article>`));
  }
  return result;
}
module.exports={pages};
