const C=require('../academy-activities.js');
const label={exercise:'Övning',scenario:'Scenario',challenge:'Praktiskt projekt',case:'Case'};
function render({A,link,esc,page}){
 const summary=`<section class="academy-progress academy-xp" aria-label="Din Academy-nivå"><p data-xp-label role="status" aria-live="polite">Nivå 1 · Ny · 0 XP</p><progress data-xp-bar max="100" value="0" aria-label="Framsteg till nästa Academy-nivå"></progress><p data-xp-next>60 XP till nästa nivå</p><p data-current-path>Välj ett lärspår eller följ färdplanen.</p><a data-next-activity class="primary-btn" href="academy-aktier.html">Starta här</a><p data-next-reason>Nästa ej avslutade lektion i färdplanen.</p><p class="note">Nivån visar din aktivitet i Academy, inte yrkeskompetens eller en certifiering. Lektioner markeras av dig; praktiska uppgifter har kontroller och självgranskning.</p><details><summary>Så räknas XP</summary><p>En lektion ger ${C.rules.lesson} XP, en ny korrekt kontroll ${C.rules.question}, en avslutad övning ${C.rules.exercise}, ett scenario ${C.rules.scenario}, ett projekt ${C.rules.challenge}, ett case ${C.rules.case} och ett lärspår ${C.rules.path}. Varje belöning räknas en gång. Repetition är fri. Sidvisningar ger inga XP. Intjänade XP behålls när du markerar en lektion för repetition.</p></details></section>`;
 const home=`<p>Följ pilotens begrepp i ordning: <a href="academy.html?competency=per-share#academyCompetencies">bolag och per aktie</a> → <a href="academy.html?competency=valuation-return#academyCompetencies">värdering</a> → <a href="academy.html?competency=real-fx#academyCompetencies">köpkraft och valuta</a>. Lärspåren nedan är frivilliga läsordningar genom materialet.</p>`+summary.replace('class="primary-btn"','class="secondary-btn"')+`<section aria-labelledby="roadmap"><h2 id="roadmap">Översikt: läsning och övningar</h2><p>Följ ordningen eller välj en etapp. Alla aktiviteter är tillgängliga.</p><ol class="academy-roadmap">${C.roadmap.map((s,i)=>`<li class="card" data-roadmap="${s.id}"><span class="academy-eyebrow">Etapp ${i+1}${s.difficulty==='advanced'?' · Avancerat':''}</span><h3>${esc(s.title)}</h3><p data-stage-status="${s.id}">Tillgänglig · 0 av ${s.lessons.length+1}</p><details><summary>Visa lektioner och milstolpe</summary><ol>${s.lessons.map(id=>`<li>${link('learn-'+id)}</li>`).join('')}<li>${link('activity-'+s.milestone,'Milstolpe: '+C.objects.find(o=>o.id===s.milestone).title)}</li></ol></details></li>`).join('')}</ol></section>
 <details class="depth-panel"><summary>Aktivitet per ämne <small>Avslutade uppgifter per område</small></summary><p>Procenten visar avklarade uppgifter i det här materialet. Den är inte ett mått på professionell behärskning.</p><div class="academy-grid">${A.categories.map(c=>`<section><h3>${esc(c.title)}</h3><progress data-skill-bar="${c.id}" max="100" value="0" aria-label="Avklarade uppgifter: ${esc(c.title)}"></progress><p data-skill="${c.id}">Inga uppgifter klara</p></section>`).join('')}</div></details>
 <details class="depth-panel"><summary>Milstolpar du har nått</summary><ul class="academy-achievements">${C.achievements.map(a=>`<li data-achievement="${a.id}">${esc(a.title)} <span>Inte nådd</span></li>`).join('')}</ul></details>
 <section aria-labelledby="practice"><h2 id="practice">Pröva och tillämpa</h2><p>Välj fritt. Numeriska svar anges i den enhet frågan anger. Du kan försöka igen utan XP-upprepning.</p>${['scenario','challenge','case','exercise'].map(type=>`<details class="depth-panel"><summary>${label[type]} · ${C.published().filter(o=>o.type===type).length} aktiviteter</summary><ul class="academy-activity-list">${C.published().filter(o=>o.type===type).map(o=>`<li>${link('activity-'+o.id)} <span data-activity-status="${o.id}">Tillgänglig</span></li>`).join('')}</ul></details>`).join('')}</section>`;
 const pages=new Map();
 for(const o of C.published()){
  const controls=q=>q.kind==='numeric'?`<label>Svar i frågans enhet<input name="answer" type="number" inputmode="decimal" step="any" required /></label>`:q.kind==='reflection'?`<label>Ditt resonemang (minst 30 ord, sparas inte)<textarea name="reflection" rows="6" required></textarea></label><ul>${q.rubric.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><label><input name="reviewed" type="checkbox" required /> Jag har granskat resonemanget mot alla kriterier.</label>`:q.options.map((option,i)=>`<label><input type="${q.kind==='multiple'?'checkbox':'radio'}" name="answer" value="${i}" />${esc(option)}</label>`).join('');
  const related=C.published().filter(n=>n.id!==o.id&&n.skill===o.skill),next=related.find(n=>n.type!==o.type)||related[0];
  pages.set(C.url(o.id),page(o.title,`${label[o.type]} i NTM Academy: ${o.context.slice(0,130)}`,`<article class="academy-lesson" data-academy-activity="${o.id}"><nav aria-label="Lärsession"><a href="academy.html#roadmap">Färdplan</a> · ${link('learn-'+o.relatedConcepts[0],'Föregående: repetera grunden')} · <a href="academy.html">Avsluta sessionen</a></nav><p class="academy-eyebrow">${label[o.type]} · ${{beginner:'Grund',intermediate:'Fördjupning',advanced:'Avancerat'}[o.difficulty]}</p><h1>${esc(o.title)}</h1><p class="academy-short">${esc(o.context)}</p><p class="note">Fiktivt undervisningsunderlag. Ingen köp- eller säljrekommendation. Rättade kontroller räknas som övning; projekt och case kräver även en självgranskning.</p><p data-activity-progress role="status">0 av ${o.questions.length} steg klara</p>
  ${o.questions.map((q,i)=>`<section class="academy-step"><h2>Steg ${i+1}${q.kind==='reflection'?' · Självgranskning':''}</h2><form data-activity-question="${q.id}" class="academy-quiz"><fieldset><legend>${esc(q.prompt)}</legend>${controls(q)}</fieldset><button type="submit" class="secondary-btn" disabled>Kontrollera och fortsätt</button><p role="status" data-answer-feedback></p><p data-question-history="${q.id}" class="note">Ännu inte kontrollerad</p></form></section>`).join('')}
  <h2>Pröva i NTM</h2><p>Använd verktyget för dina egna antaganden. Att öppna en länk ger inga XP; övningens belöning bygger på stegen ovan.</p><div class="academy-next">${o.relatedEntityIds.map(id=>link(id,null,'data-academy-tool')).join('')}</div><h2>Repetera begreppen</h2><div class="academy-related">${o.relatedConcepts.map(id=>link('learn-'+id)).join('')}</div><details><summary>Källa och metod</summary><p>NTM:s egna syntetiska övningar. Belopp och antaganden är pedagogiska exempel. Definitioner, källor och begränsningar finns i de relaterade lektionerna. Svarstext sparas inte; endast kontrollens ID, utfall och tidpunkt ingår i lokal lärhistorik. Projektens text granskas av dig, inte av AI.</p></details><div class="academy-next">${next?link('activity-'+next.id,'Nästa aktivitet: '+next.title):'<a href="academy.html#roadmap">Till färdplanen</a>'}</div>${summary}</article>`));
 }
 return {home,pages,summary};
}
module.exports={render};
