/* Synthetic fixtures exist only in process or a caller-supplied test response. */
'use strict';
const {performance}=require('node:perf_hooks'),zlib=require('node:zlib'),Core=require('../knowledge-core.js'),raw=require('../docs/internal/knowledge/catalog.cjs');
function fixture(size){const data=structuredClone(raw);data.synthetic=true;for(let i=data.entries.length;i<size;i++){const e=structuredClone(raw.entries[i%raw.entries.length]);Object.assign(e,{id:'synthetic-'+i,slug:'synthetic-'+i,question:'Synthetic benchmark '+i+' '+e.question,aliases:['synthetic alias '+i],featured:false});delete e.relatedAnswers;const concept={id:'fixture-concept-'+i,term:'Synthetic metric '+i,category:e.category,synonyms:['fixture term '+i],abbreviations:[],related:[]};data.knowledgeConcepts.push(concept);e.conceptRefs.push(concept.id);data.entries.push(e);}return data;}
function run(){const rows=[];for(const size of [100,500,1200]){const memory=process.memoryUsage().heapUsed,start=performance.now(),data=fixture(size),fixtureMs=performance.now()-start,t0=performance.now(),index=Core.index(data),indexMs=performance.now()-t0,t1=performance.now(),K=Core.create(index),engineMs=performance.now()-t1,t2=performance.now(),generated=require('./build_knowledge.cjs').build(data,{synthetic:true}),generationMs=performance.now()-t2;
 const measure=fn=>{const samples=[];for(let i=0;i<100;i++){const t=performance.now();fn();samples.push(performance.now()-t);}samples.sort((a,b)=>a-b);return {medianMs:samples[50],p95Ms:samples[95],maxMs:samples[99]};};
 rows.push({size,fixtureMs,indexMs,engineMs,generationMs,indexBytes:Buffer.byteLength(JSON.stringify(index)),indexGzipBytes:zlib.gzipSync(JSON.stringify(index)).length,fullPublicBytes:Buffer.byteLength(JSON.stringify(Core.project(data))),landingBytes:Buffer.byteLength(generated.pages.get('fragor-svar.html')),initialAnswerCards:(generated.pages.get('fragor-svar.html').match(/data-knowledge-card=/g)||[]).length,heapDeltaBytes:process.memoryUsage().heapUsed-memory,search:measure(()=>K.search('vinst')),ask:measure(()=>K.respond('Vad betyder P/E?')),askNoCoverage:measure(()=>K.respond('unknownterm')),askTypo:measure(()=>K.respond('diversifierinh')),askClarification:measure(()=>K.respond('avkastning')),category:measure(()=>K.search('','metrics').slice(0,12)),relationships:measure(()=>K.entries.flatMap(e=>e.relatedAnswers||[]).slice(0,20))});}
 return {version:1,environment:process.version,method:'Synthetic in-memory catalogs; 100 warmed samples; Node heap delta includes generated pages and is not isolated retained heap; no network/CPU throttling.',rows};}
if(require.main===module){if(process.argv[2]==='--fixture')process.stdout.write(JSON.stringify(Core.index(fixture(Number(process.argv[3])))));else process.stdout.write(JSON.stringify(run(),null,2)+'\n');}
module.exports={fixture,run};
