/* Presentation only. Inputs are the canonical reviewed projections and relation registry. */
const fs=require('node:fs'),path=require('node:path');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={prerequisite:'Förstå grunden',deeper:'Fördjupa',comparison:'Jämför med','common-confusion':'Vanlig förväxling','related-metric':'Närliggande begrepp','next-question':'Nästa fråga',application:'Använd i praktiken'};
function landing(K){return fs.readFileSync(path.join(__dirname,'knowledge_landing.html'),'utf8')+`<section id="knowledgeFallback"><h2>Fråga NTM</h2><p>Frågeläget kräver JavaScript. Läs granskade svar direkt eller välj ett område.</p><p><a href="${K.url('pe')}">Vad betyder P/E?</a></p><nav aria-label="Kunskapsområden">${K.categories.map(c=>`<p id="category-${c.id}"><a href="fragor-svar-omrade-${c.id}-1.html">${esc(c.title)}</a></p>`).join('')}</nav></section>`;}
function answer(e,K,rows,rule){
 const related=(e.relatedAnswers||[]).filter(r=>K.publicEntries().some(x=>x.id===r.id));
 const c=e.sections?.comparison;
 const compare=c?`<section><h2>Jämförelse</h2><table class="comparison"><caption>${esc(e.question)}</caption><thead><tr><th scope="col">Aspekt</th><th scope="col">${esc(c.leftLabel)}</th><th scope="col">${esc(c.rightLabel)}</th></tr></thead><tbody>${c.axes.map(x=>`<tr><th scope="row">${esc(x.label)}</th><td>${esc(x.left)}</td><td>${esc(x.right)}</td></tr>`).join('')}</tbody></table><p>${esc(c.limitations)}</p></section>`:'';
 return `<article class="knowledge-answer" data-knowledge-answer="${e.id}"><nav aria-label="Brödsmulor"><a href="fragor-svar.html">Fråga NTM</a> / <a href="fragor-svar.html#category-${e.category}">${esc(K.categories.find(c=>c.id===e.category).title)}</a></nav><p class="section-kicker">NTM Kunskap · Granskat svar</p><h1>${esc(e.question)}</h1><section class="knowledge-short"><h2>Kort svar</h2><p>${esc(e.shortAnswer)}</p></section><details class="knowledge-depth" open><summary>Fördjupa · exempel &amp; begränsningar</summary><h2>${e.sections?.interpretation?'Tolkning':'Förklaring'}</h2><p>${esc(e.fullAnswer)}</p>${e.example?`<section class="knowledge-example"><h2>Exempel — förenklat</h2><p>${esc(e.example)}</p></section>`:''}<h2>Viktigt att tänka på</h2><p>${esc(e.caveats)}</p></details>${compare}${rule}
 <details class="knowledge-method"><summary>Källor &amp; granskning</summary><p>Granskat ${esc(e.reviewedAt)}. Innehållsversion ${e.contentVersion}.</p>${e.sources.map(s=>`<section><p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a> · kontrollerad ${esc(s.reviewedAt)}</p>${s.checked?`<p>${esc(s.checked)}</p>`:''}${s.limitations?`<p>${esc(s.limitations)}</p>`:''}</section>`).join('')}</details>
 ${rows.length||e.practiceId?`<section class="knowledge-related"><h2>Använd det</h2>${e.practiceId?`<p><a href="academy-activity-${esc(e.practiceId)}.html" target="_blank" rel="noopener noreferrer" data-knowledge-related>Träna i Academy</a></p>`:''}${rows.map(r=>`<p><a href="${esc(r.destination.url)}" target="_blank" rel="noopener noreferrer" data-knowledge-related data-relation-id="${esc(r.id)}">${r.destination.type==='learn'?'Träna i Academy: ':r.destination.type==='research'?'Öppna ':r.destination.type==='macro'?'Se i Makro: ':'Testa: '}${esc(r.destination.title)} ↗</a></p>`).join('')}<p class="note">Öppnas i ny flik. Svaret är kvar här. Inga värden eller texter förs över.</p></section>`:''}
 ${related.length?`<section class="knowledge-related"><h2>Fortsätt utforska</h2>${related.map(r=>`<p><small>${types[r.type]||'Fördjupa'}</small><br><a href="${K.url(r.id)}">${esc(K.entries.find(x=>x.id===r.id).question)}</a></p>`).join('')}</section>`:''}
 <nav class="knowledge-bottom" aria-label="Fortsätt läsa"><a href="fragor-svar.html?id=${e.id}">Fortsätt i Fråga NTM</a><a href="fragor-svar.html?mode=explore">Utforska kunskapsbanken</a></nav></article>`.replace(/[ \t]+\n/g,'\n');
}
module.exports={landing,answer};
