/* Local editorial tools. Never promote content or reset a review date automatically. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),Core=require('../knowledge-core.js'),raw=require('../docs/internal/knowledge/catalog.cjs'),Q=require('./knowledge_quality.cjs'),rules=require('../data/rule-registry.json');
const clone=v=>JSON.parse(JSON.stringify(v)),today=()=>new Date().toISOString().slice(0,10);
function report(data=raw){
 const entries=data.entries,concepts=data.knowledgeConcepts,possibleDuplicates=[];
 for(let i=0;i<entries.length;i++)for(let j=i+1;j<entries.length;j++){const a=entries[i],b=entries[j],words=new Set(Core.normalize(a.question).split(' ')),other=new Set(Core.normalize(b.question).split(' ')),intersection=[...words].filter(t=>other.has(t)).length,similarity=intersection/(new Set([...words,...other]).size);if(a.intent===b.intent&&a.conceptRefs.some(id=>b.conceptRefs.includes(id))||similarity>.65)possibleDuplicates.push({ids:[a.id,b.id],intents:[a.intent,b.intent],samePrimaryConcept:a.conceptRefs[0]===b.conceptRefs[0],sharedConcepts:a.conceptRefs.filter(id=>b.conceptRefs.includes(id)),similarity,action:'editorial-review-only'});}
 return {version:1,asOf:today(),answers:entries.length,publicAnswers:entries.filter(Core.visible).length,concepts:concepts.length,byIntent:Object.fromEntries(require('./knowledge_scale_quality.cjs').intents.map(i=>[i,entries.filter(e=>e.intent===i).length])),coverage:concepts.map(c=>({id:c.id,answers:entries.filter(e=>e.conceptRefs.includes(c.id)).map(e=>({id:e.id,intent:e.intent,status:e.status}))})),possibleDuplicates,overdue:entries.filter(e=>e.reviewDue&&e.reviewDue<today()).map(e=>e.id),missingReviewSchedule:entries.filter(e=>!e.reviewDue).map(e=>e.id),needsUpdate:entries.filter(e=>e.status==='needs-update').map(e=>e.id),unmappedClaims:entries.filter(e=>!['shortAnswer','fullAnswer','caveats'].every(k=>e.sources.some(s=>s.supports?.includes(k)))).map(e=>e.id),inheritedNotIndependent:entries.filter(e=>e.editorial.approval==='inherited-not-independent').map(e=>e.id),orphanConcepts:concepts.filter(c=>!entries.some(e=>e.conceptRefs.includes(c.id))).map(c=>c.id),unintegrated:entries.filter(e=>!e.relatedEntityIds?.length&&!e.relatedLessonIds?.length&&!e.relatedAnswers?.length).map(e=>e.id),formulaRevalidation:entries.filter(e=>e.sections?.formula).map(e=>({id:e.id,template:e.sections.formula.template,example:e.sections.formula.example,independentHumanCheck:'pending'})),ruleVersions:entries.filter(e=>e.ruleId).map(e=>({id:e.id,rule:rules.rules.find(r=>r.id===e.ruleId)})),sourceChecks:'Run sources command; HTTP success is not claim verification.'};
}
function template(kind,id){const originals={definition:'eps',formula:'pe',comparison:'forward',interpretation:'debt',sensitive:'isk'};if(!originals[kind]||!/^[a-z][a-z0-9-]+$/.test(id))throw Error('Use definition|formula|comparison|interpretation|sensitive and a stable slug ID');const e=clone(raw.entries.find(e=>e.id===originals[kind]));Object.assign(e,{id,slug:id,question:'UTKAST: '+e.question,status:'draft',reviewedAt:null,aliases:[id],featured:false,contentVersion:1,editorial:{owner:'NTM owner',approval:'pending',reviewer:null,reviewedAt:null,changeNote:'Draft template copied from '+originals[kind]+'; replace prose, aliases and evidence before approval.'}});delete e.publishedAt;delete e.practiceId;delete e.internalReview;delete e.internalEditorialNotes;delete e.relatedAnswers;if(kind==='sensitive'){e.jurisdiction='SE';e.period=String(rules.rules.find(r=>r.id===e.ruleId).effectiveYear);}return e;}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function preview(e){return `<!doctype html><html lang="sv"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="robots" content="noindex,nofollow"><title>Lokalt utkast</title><main><h1>UTKAST – inte publicerat eller godkänt</h1><h2>${esc(e.question)}</h2>${['shortAnswer','fullAnswer','example','caveats'].map(k=>`<h3>${k}</h3><p>${esc(e[k])}</p>`).join('')}<h3>Strukturerade delar</h3><pre>${esc(JSON.stringify(e.sections,null,2))}</pre><h3>Källunderlag</h3><pre>${esc(JSON.stringify(e.sources,null,2))}</pre></main></html>`;}
async function sources(){const urls=[...new Set(raw.entries.flatMap(e=>e.sources.map(s=>s.url)))],result=[];for(let i=0;i<urls.length;i+=4)result.push(...await Promise.all(urls.slice(i,i+4).map(async url=>{try{const r=await fetch(url,{method:'HEAD',signal:AbortSignal.timeout(10000),redirect:'follow'});return {url,status:r.status,result:r.ok?'reachable-not-claim-verified':r.status===404||r.status===410?'broken':'unverified-access-restricted'};}catch{return {url,result:'unverified-network'};}})));return result;}
async function main(){const [command,arg,out]=process.argv.slice(2);let result;
 if(command==='validate'){const errors=Q.validate(raw,rules);if(errors.length)throw Error(errors.join('\n'));result={valid:true,answers:raw.entries.length};}
 else if(command==='report')result=maintenance();
 else if(command==='sources')result=await sources();
 else if(command==='template'){result=template(arg,out);const file=process.argv[5];if(file){if(!path.resolve(file).startsWith(path.resolve('docs/internal/knowledge')+path.sep))throw Error('Templates must stay in the internal Knowledge directory');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(result,null,2)+'\n',{flag:'wx'});return;}}
 else if(command==='preview'){const e=JSON.parse(fs.readFileSync(arg,'utf8'));const data=clone(raw),existing=data.entries.findIndex(a=>a.id===e.id);if(existing<0)data.entries.push(e);else data.entries[existing]=e;const errors=Q.validate(data,rules);if(errors.length)throw Error(errors.join('\n'));if(!out||!path.resolve(out).startsWith(path.resolve('docs')+path.sep))throw Error('Preview must stay under docs/, outside public staging');fs.writeFileSync(out,preview(e));return;}
 else throw Error('Commands: validate | report | sources | template KIND ID | preview INPUT docs/PREVIEW.html');
 process.stdout.write(JSON.stringify(result,null,2)+'\n');
}
if(require.main===module)main().catch(e=>{console.error(e.message);process.exitCode=1;});
function maintenance(data=raw){return {...report(data),answerMaintenance:data.entries.map(e=>({id:e.id,intent:e.intent,status:e.status,reviewedAt:e.reviewedAt,reviewAgeDays:e.reviewedAt?Math.floor((Date.now()-Date.parse(e.reviewedAt))/86400000):null,reviewDue:e.reviewDue||null,contexts:e.sections?.inline?.contexts||[],sourceClaims:['shortAnswer','fullAnswer','caveats'].map(section=>({section,mapped:e.sources.some(s=>s.supports?.includes(section)),independentlyChecked:e.sources.some(s=>s.supports?.includes(section)&&s.evidenceStatus==='checked')})),formula:e.sections?.formula?.template||null,workedExample:!!e.example,integrations:[...e.relatedEntityIds,...e.relatedLessonIds]}))};}
module.exports={report:maintenance,template,preview};
